import os
from urllib.request import Request, urlopen
import requests

from bs4 import BeautifulSoup
import pdfkit
from ebooklib import epub


def downloadFile(URL=None):
    #req = Request(
    #    URL,
    #    headers={'User-Agent': 'Mozilla/5.0'})
    #data = urlopen(req).read()
    headers = {
        'USER-AGENT': 'Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405'}

    data = requests.get(URL, headers=headers).content
    text = data.decode('utf-8')  # a `str`; this step can't be used if data is binary
    return text

def tubosquid():
    files = [
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-139.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-140.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-141.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-142.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-143.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-144.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-145.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-royal-capital.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-royal-capital_5.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-royal-capital_87.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-146.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths_6.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths_7.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths_63.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-147.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-148.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-149.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-150.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s22.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-151.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-152.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-153.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-154.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-155.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s23.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-156.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-157.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-158.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-159.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-160.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s24.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-161.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-162.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-163.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-164.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-165.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s25.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-166.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-167.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-168.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-169.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-170.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s26.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-divine-word.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-171.html",
    "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ka-chapter-172.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-173.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-174.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-searching-for.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-magician.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-175.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s27.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-176.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-177.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-178.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-179.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-180.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s28.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-181.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-182.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-183.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-184.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-185.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s29.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-186.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-187.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-188.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-189.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-190.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-elf-village-1.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-elf-village-2.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-elf-village-3.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-because-i-am.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-191.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-192.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-193.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-194.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-195.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-before-war.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-196.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-197.html",
    "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-198.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-199.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-200.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_2.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_40.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_30.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_3.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_18.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_45.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_99.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_4.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_79.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_78.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-201.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-202.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-203.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-204.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-205.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-1.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-character.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-206.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-207.html",
    "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-blood-1.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-2.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-3.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-2.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-4.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-5.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-6.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-7.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-8.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-3.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-9.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-10.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-208.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-209.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-210.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-4.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-11.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-12.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-13.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-14.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-15.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-5.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-16.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-17.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-18.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-211.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-212.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-6.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-19.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-20.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-21.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-regular-reports-of.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-pope-and.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-7.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-22.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-23.html",
    "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-blood-24.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-25.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-26.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-8.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-revolving-lantern.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-rumor-of-adventurer.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-adventurers-vs-ogre.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-empire-knights-vs.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-old-man2-vs-ogre.html",
    "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-oni-9.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-sword-king-and.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-pope-and-ninja.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-country-of.html",
    "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-previous-sword.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-sword-god-vs-ogre.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-10.html",
    "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-vs-oni-1.html",
    "http://turb0translation.blogspot.my/2015/11/kumo-desu-ga-nani-ka-oni-vs-oni-2.html"
    ]

    out = r'C:\Users\Maoserr\Desktop\Out'
    out_htmls = []
    for i in range(0,len(files)-1):
        base_name = os.path.splitext(os.path.basename(files[i]))[0]
        curr_html = os.path.join(out,str(i)+base_name+".html")
        print("Page "+str(i))
        out_htmls.append(curr_html)
        if os.path.exists(curr_html):
            continue
        txt = downloadFile(files[i])
        soup = BeautifulSoup(txt, 'html.parser')
        body=soup.find_all('div',class_='post-body')
        with open(curr_html,'wb') as f:
            f.write(body[0].encode("utf-8"))

    options = {
        'encoding': "UTF-8"
    }
    #res = pdfkit.from_file(out_htmls,os.path.join(out,"Kumo_Tubo.pdf"),options=options)


    book = epub.EpubBook()

    # set metadata
    book.set_identifier('id123456')
    book.set_title('Kumo Desu Ga')
    book.set_language('en')

    book.add_author('Author')

    spine = ['nav']
    for i in range(0,len(out_htmls)-1):
        base_name = os.path.splitext(os.path.basename(out_htmls[i]))[0]
        # create chapter
        c1 = epub.EpubHtml(title=base_name, file_name=base_name+".xhtml")
        with open(out_htmls[i],'rb') as f:
            c1.content=f.read()
        spine.append(c1)

        # add chapter
        book.add_item(c1)

    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = spine
    # write to the file
    epub.write_epub(os.path.join(out,"Kumo_Tubo.epub"), book, {})

def raisedead():
    files = [
        {'href': r'http://raisingthedead.ninja/2015/11/09/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a2/',
         'title': "Kumo Desu Ga, Nani Ka? Oni vs Oni ③"},
        {'href': r'http://raisingthedead.ninja/2015/11/11/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a3/',
         'title': "Kumo Desu Ga, Nani Ka? Oni Vs Oni ④"},
        {'href': r'http://raisingthedead.ninja/2015/11/11/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a4/',
         'title': "Kumo Desu Ga, Nani Ka? Oni vs Oni ⑤"},
        {'href': r'http://raisingthedead.ninja/2015/11/11/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a5/',
         'title': "Kumo Desu Ga, Nani Ka? Oni VS Oni ⑥"},
        {'href': r'http://raisingthedead.ninja/2015/11/19/kumo-desu-ga-nani-ka-213/',
         'title': "Kumo Desu Ga, Nani Ka? 213"},
        {'href': r'http://raisingthedead.ninja/2015/11/20/kumo-desu-ga-nani-ka-214/',
         'title': "Kumo Desu Ga, Nani Ka? 214"},
        {'href': r'http://raisingthedead.ninja/2015/12/01/kumo-desu-ga-nani-ka-215/',
         'title': "Kumo Desu Ga, Nani Ka? 215"},
        {'href': r'http://raisingthedead.ninja/2015/12/01/kumo-desu-ga-nani-ka-216/',
         'title': "Kumo Desu Ga, Nani Ka? 216"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-217/',
         'title': "Kumo desu ga, Nani ka? 217"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-218/',
         'title': "Kumo desu ga, Nani ka? 218"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-219/',
         'title': "Kumo desu ga, Nani ka? 219"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-220/',
         'title': "Kumo desu ga, Nani ka? 220"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/oshiete-d-sensei-lesson-1/',
         'title': "Oshiete D-sensei! Lesson 1"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-221/',
         'title': "Kumo desu ga, Nani ka? 221"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-222/',
         'title': "Kumo desu ga, Nani ka? 222"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-223/',
         'title': "Kumo desu ga, Nani ka? 223"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-224/',
         'title': "Kumo desu ga, Nani ka? 224"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-225/',
         'title': "Kumo desu ga, Nani ka? 225"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-226/',
         'title': "Kumo desu ga, Nani ka? 226"},
        {'href': r'http://raisingthedead.ninja/2016/01/27/kumo-desu-ga-nani-ka-227/',
         'title': "Kumo desu ga, Nani ka? 227"},
        {'href': r'http://raisingthedead.ninja/2016/01/27/kumo-desu-ga-nani-ka-228/',
         'title': "Kumo desu ga, Nani ka? 228"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-229/',
         'title': "Kumo desu ga, Nani ka? 229"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-230/',
         'title': "Kumo desu ga, Nani ka? 230"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-231/',
         'title': "Kumo desu ga, Nani ka? 231"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-232/',
         'title': "Kumo desu ga, Nani ka? 232"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-233/',
         'title': "Kumo desu ga, Nani ka? 233"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-234/',
         'title': "Kumo desu ga, Nani ka? 234"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-235/',
         'title': "Kumo desu ga, Nani ka? 235"},
        {'href': r'http://raisingthedead.ninja/2016/01/29/kumo-desu-ga-nani-ka-236/',
         'title': "Kumo desu ga, Nani ka? 236"},
        {'href': r'http://raisingthedead.ninja/2016/01/30/kumo-desu-ga-nani-ka-237/',
         'title': "Kumo desu ga, Nani ka? 237"},
        {'href': r'http://raisingthedead.ninja/2016/01/31/6231/', 'title': "Kumo desu ga, Nani ka? 238"},
        {'href': r'http://raisingthedead.ninja/2016/02/01/kumo-desu-ga-nani-ka-239/',
         'title': "Kumo desu ga, Nani ka? 239"},
        {'href': r'http://raisingthedead.ninja/2016/02/02/kumo-desu-ga-nani-ka-240/',
         'title': "Kumo desu ga, Nani ka? 240"},
        {'href': r'http://raisingthedead.ninja/2016/02/05/the-commanders-bad-day/',
         'title': "Kumo Desu ga, Nani ka? The Commander’s Bad Day"},
        {'href': r'http://raisingthedead.ninja/2016/02/06/kumo-desu-ga-nani-ka-ss-christmas/',
         'title': "Kumo Desu ga, Nani ka? SS &#8211; Christmas"},
        {'href': r'http://raisingthedead.ninja/2016/02/07/kumo-desu-ga-nani-ka-241/',
         'title': "Kumo desu ga, Nani ka? 241"},
        {'href': r'http://raisingthedead.ninja/2016/02/08/kumo-desu-ga-nani-ka-242/',
         'title': "Kumo desu ga, Nani ka? 242"},
        {'href': r'http://raisingthedead.ninja/2016/02/09/kumo-desu-ga-nani-ka-243/',
         'title': "Kumo desu ga, Nani ka? 243"},
        {'href': r'http://raisingthedead.ninja/2016/02/10/kumo-desu-ga-nani-ka-244/',
         'title': "Kumo desu ga, Nani ka? 244"},
        {'href': r'http://raisingthedead.ninja/2016/02/11/kumo-desu-ga-nani-ka-245/',
         'title': "Kumo desu ga, Nani ka? 245"},
        {'href': r'http://raisingthedead.ninja/2016/02/12/kumo-desu-ga-nani-ka-246/',
         'title': "Kumo desu ga, Nani ka? 246"},
        {'href': r'http://raisingthedead.ninja/2016/02/14/kumo-desu-ga-nani-ka-247/',
         'title': "Kumo desu ga, Nani ka? 247"},
        {'href': r'http://raisingthedead.ninja/2016/02/15/kumo-desu-ga-nani-ka-248/',
         'title': "Kumo desu ga, Nani ka? 248"},
        {'href': r'http://raisingthedead.ninja/2016/02/16/kumo-desu-ga-nani-ka-249/',
         'title': "Kumo desu ga, Nani ka? 249"},
        {'href': r'http://raisingthedead.ninja/2016/02/17/kumo-desu-ga-nani-ka-250/',
         'title': "Kumo desu ga, Nani ka? 250"},
        {'href': r'http://raisingthedead.ninja/2016/02/18/kumo-desu-ga-nani-ka-251/',
         'title': "Kumo desu ga, Nani ka? 251"},
        {'href': r'http://raisingthedead.ninja/2016/02/19/kumo-desu-ga-nani-ka-252/',
         'title': "Kumo desu ga, Nani ka? 252"},
        {'href': r'http://raisingthedead.ninja/2016/02/20/kumo-desu-ga-nani-ka-253/',
         'title': "Kumo desu ga, Nani ka? 253"},
        {'href': r'http://raisingthedead.ninja/2016/02/21/kumo-desu-ga-nani-ka-254/',
         'title': "Kumo desu ga, Nani ka? 254"},
        {'href': r'http://raisingthedead.ninja/2016/02/21/kumo-desu-ga-nani-ka-255/',
         'title': "Kumo desu ga, Nani ka? 255"},
        {'href': r'http://raisingthedead.ninja/2016/02/22/kumo-desu-ga-nani-ka-256/',
         'title': "Kumo desu ga, Nani ka? 256"},
        {'href': r'http://raisingthedead.ninja/2016/02/23/kumo-desu-ga-nani-ka-blood-27/',
         'title': "Kumo desu ga, Nani ka? Blood 27"},
        {'href': r'http://raisingthedead.ninja/2016/02/24/kumo-desu-ga-nani-ka-oni-11/',
         'title': "Kumo desu ga, Nani ka? Oni 11"},
        {'href': r'http://raisingthedead.ninja/2016/02/25/kumo-desu-ga-nani-ka-blood-28/',
         'title': "Kumo desu ga, Nani ka? Blood 28"},
        {'href': r'http://raisingthedead.ninja/2016/02/26/kumo-desu-ga-nani-ka-oni-12/',
         'title': "Kumo desu ga, Nani ka? Oni 12"},
        {'href': r'http://raisingthedead.ninja/2016/02/27/kumo-desu-ga-nani-ka-blood-29/',
         'title': "Kumo desu ga, Nani ka? Blood 29"},
        {'href': r'http://raisingthedead.ninja/2016/02/28/kumo-desu-ga-nani-ka-oni-13/',
         'title': "Kumo desu ga, Nani ka? Oni 13"},
        {'href': r'http://raisingthedead.ninja/2016/02/29/kumo-desu-ga-nani-ka-blood-30/',
         'title': "Kumo desu ga, Nani ka? Blood 30"},
        {'href': r'http://raisingthedead.ninja/2016/03/04/kumo-desu-ga-nani-ka-257/',
         'title': "Kumo desu ga, Nani ka? 257"},
        {'href': r'http://raisingthedead.ninja/2016/03/05/kumo-desu-ga-nani-ka-the-popes-deliberations/',
         'title': "Kumo Desu ga, Nani ka? The Pope’s Deliberations"},
        {'href': r'http://raisingthedead.ninja/2016/03/06/kumo-desu-ga-nani-ka-the-popes-torment/',
         'title': "Kumo Desu ga, Nani ka? The Pope’s Torment"},
        {'href': r'http://raisingthedead.ninja/2016/03/07/kumo-desu-ga-nani-ka-258/',
         'title': "Kumo desu ga, Nani ka? 258"},
        {'href': r'http://raisingthedead.ninja/2016/03/09/kumo-desu-ga-nani-ka-259/',
         'title': "Kumo desu ga, Nani ka? 259"},
        {'href': r'http://raisingthedead.ninja/2016/03/11/kumo-desu-ga-nani-ka-oni-14/',
         'title': "Kumo desu ga, Nani ka? Oni 14"},
        {'href': r'http://raisingthedead.ninja/2016/03/14/kumo-desu-ga-nani-ka-blood-31/',
         'title': "Kumo desu ga, Nani ka? Blood 31"},
        {'href': r'http://raisingthedead.ninja/2016/03/16/kumo-desu-ga-nani-ka-260/',
         'title': "Kumo desu ga, Nani ka? 260"},
        {'href': r'http://raisingthedead.ninja/2016/06/17/the-return-of-the-spider/',
         'title': "The Return of the Spider"},
        {'href': r'http://raisingthedead.ninja/2016/06/17/kumo-desu-ga-nani-ka-oni-15/',
         'title': "Kumo desu ga, Nani ka? Oni 15"},
        {'href': r'http://raisingthedead.ninja/2016/06/18/kumo-desu-ga-nani-ka-blood-32/',
         'title': "Kumo desu ga, Nani ka? Blood 32"},
        {'href': r'http://raisingthedead.ninja/2016/06/19/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a0/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ①"},
        {'href': r'http://raisingthedead.ninja/2016/06/19/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a1/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ②"},
        {'href': r'http://raisingthedead.ninja/2016/06/20/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a2/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ③"},
        {'href': r'http://raisingthedead.ninja/2016/06/20/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a3/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ④"},
        {'href': r'http://raisingthedead.ninja/2016/06/21/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a4/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑤"},
        {'href': r'http://raisingthedead.ninja/2016/06/22/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a5/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑥"},
        {'href': r'http://raisingthedead.ninja/2016/06/23/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a6/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑦"},
        {'href': r'http://raisingthedead.ninja/2016/06/24/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a7/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑧"},
        {'href': r'http://raisingthedead.ninja/2016/07/01/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a8/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑨"},
        {'href': r'http://raisingthedead.ninja/2016/07/02/kumo-desu-ga-nani-ka-informal-conference-hidden/',
         'title': "Kumo desu ga, Nani ka? Informal Conference &#8211; hidden"},
        {'href': r'http://raisingthedead.ninja/2016/07/02/kumo-desu-ga-nani-ka-oni-16/',
         'title': "Kumo desu ga, Nani ka? Oni 16"},
        {'href': r'http://raisingthedead.ninja/2016/07/03/kumo-desu-ga-nani-ka-blood-33/',
         'title': "Kumo desu ga, Nani ka? Blood 33"},
        {'href': r'http://raisingthedead.ninja/2016/07/07/kumo-desu-ga-nani-ka-oni-17/',
         'title': "Kumo desu ga, Nani ka? Oni 17"},
        {'href': r'http://raisingthedead.ninja/2016/07/10/kumo-desu-ga-nani-ka-261/',
         'title': "Kumo desu ga, Nani ka? 261"},
        {'href': r'http://raisingthedead.ninja/2016/07/16/kumo-desu-ga-nani-ka-262/',
         'title': "Kumo desu ga, Nani ka? 262"},
        {'href': r'http://raisingthedead.ninja/2016/07/24/kumo-desu-ga-nani-ka-263/',
         'title': "Kumo desu ga, Nani ka? 263"},
        {'href': r'http://raisingthedead.ninja/2016/07/31/kumo-desu-ga-nani-ka-264/',
         'title': "Kumo desu ga, Nani ka? 264"},
        {'href': r'http://raisingthedead.ninja/2016/08/16/kumo-desu-ga-nani-ka-265/',
         'title': "Kumo desu ga, Nani ka? 265"},
        {
            'href': r'http://raisingthedead.ninja/2016/08/23/kumo-desu-ga-nani-ka-the-second-informal-conference-%e2%91%a0/',
            'title': "Kumo desu ga, Nani ka? The Second Informal Conference ①"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/07/kumo-desu-ga-nani-ka-the-second-informal-conference-%e2%91%a1/',
            'title': "Kumo desu ga, Nani ka? The Second Informal Conference ②"},
        {'href': r'http://raisingthedead.ninja/2016/09/10/kumo-desu-ga-nani-ka-the-demon-king-and-the-pope/',
         'title': "Kumo desu ga, Nani ka? The Demon King and the Pope"},
        {'href': r'http://raisingthedead.ninja/2016/09/11/kumo-desu-ga-nani-ka-the-oni-and-the-ninja/',
         'title': "Kumo desu ga, Nani ka? The Oni and the Ninja"},
        {'href': r'http://raisingthedead.ninja/2016/09/11/kumo-desu-ga-nani-ka-the-vampire-the-oni-and-the-ninja/',
         'title': "Kumo desu ga, Nani ka? The Vampire, the Oni and the Ninja"},
        {'href': r'http://raisingthedead.ninja/2016/09/11/kumo-desu-ga-nani-ka-266/',
         'title': "Kumo desu ga, Nani ka? 266"},
        {'href': r'http://raisingthedead.ninja/2016/09/16/kumo-desu-ga-nani-ka-267/',
         'title': "Kumo desu ga, Nani ka? 267"},
        {'href': r'http://raisingthedead.ninja/2016/09/17/kumo-desu-ga-nani-ka-268/',
         'title': "Kumo desu ga, Nani ka? 268"},
        {'href': r'http://raisingthedead.ninja/2016/09/18/kumo-desu-ga-nani-ka-269/',
         'title': "Kumo desu ga, Nani ka? 269"},
        {'href': r'http://raisingthedead.ninja/2016/09/19/kumo-desu-ga-nani-ka-270/',
         'title': "Kumo desu ga, Nani ka? 270"},
        {'href': r'http://raisingthedead.ninja/2016/09/19/kumo-desu-ga-nani-ka-271/',
         'title': "Kumo desu ga, Nani ka? 271"},
        {'href': r'http://raisingthedead.ninja/2016/09/20/kumo-desu-ga-nani-ka-272/',
         'title': "Kumo desu ga, Nani ka? 272"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/21/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-tagawa-kunihiko/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War &#8211; The situation of Tagawa Kunihiko"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/22/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-kushitani-asaka-and-orel/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Kushitani Asaka and Aurel"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/23/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-merazofis/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Merazofis"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/24/kumo-desu-ga-nani-ka-before-the-human-demon-great-war-the-situation-of-ronant/',
            'title': "Kumo desu ga, Nani ka? Before The Human-Demon Great War &#8211; The situation of Ronant"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/25/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-wrath/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War &#8211; The situation of Wrath"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/26/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-sophia/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Sophia"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/27/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-blow/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Blow"},
        {'href': r'http://raisingthedead.ninja/2016/09/28/kumo-desu-ga-nani-ka-273/',
         'title': "Kumo desu ga, Nani ka? 273"},
        {'href': r'http://raisingthedead.ninja/2016/09/29/kumo-desu-ga-nani-ka-274/',
         'title': "Kumo desu ga, Nani ka? 274"},
        {'href': r'http://raisingthedead.ninja/2016/09/30/kumo-desu-ga-nani-ka-275/',
         'title': "Kumo desu ga, Nani ka? 275"},
        {'href': r'http://raisingthedead.ninja/2016/10/05/kumo-desu-ga-nani-ka-276/',
         'title': "Kumo desu ga, Nani ka? 276"},
        {'href': r'http://raisingthedead.ninja/2016/10/06/kumo-desu-ga-nani-ka-277/',
         'title': "Kumo desu ga, Nani ka? 277"},
        {'href': r'http://raisingthedead.ninja/2016/10/08/kumo-desu-ga-nani-ka-278/',
         'title': "Kumo desu ga, Nani ka? 278"},
        {'href': r'http://raisingthedead.ninja/2016/10/09/kumo-desu-ga-nani-ka-279/',
         'title': "Kumo desu ga, Nani ka? 279"},
        {'href': r'http://raisingthedead.ninja/2016/10/10/kumo-desu-ga-nani-ka-280/',
         'title': "Kumo desu ga, Nani ka? 280"},
        {'href': r'http://raisingthedead.ninja/2016/10/14/kumo-desu-ga-nani-ka-the-elf-leaders-miscalculation/',
         'title': "Kumo desu ga, Nani ka? The Elf Leader’s Miscalculation"},
        {'href': r'http://raisingthedead.ninja/2016/10/16/kumo-desu-ga-nani-ka-blood-34/',
         'title': "Kumo desu ga, Nani ka? Blood 34"},
        {'href': r'http://raisingthedead.ninja/2016/10/18/kumo-desu-ga-nani-ka-oni-18/',
         'title': "Kumo desu ga, Nani ka? Oni 18"},
        {'href': r'http://raisingthedead.ninja/2016/10/23/kumo-desu-ga-nani-ka-281/',
         'title': "Kumo desu ga, Nani ka? 281"},
        {'href': r'http://raisingthedead.ninja/2016/10/24/kumo-desu-ga-nani-ka-282/',
         'title': "Kumo desu ga, Nani ka? 282"},
        {'href': r'http://raisingthedead.ninja/2016/10/25/kumo-desu-ga-nani-ka-a-flat-chest-is-a-status-symbol/',
         'title': "Kumo desu ga, Nani ka? A flat chest is a status symbol!"},
        {'href': r'http://raisingthedead.ninja/2016/10/28/kumo-desu-ga-nani-ka-283/',
         'title': "Kumo desu ga, Nani ka? 283"},
        {
            'href': r'http://raisingthedead.ninja/2016/10/30/kumo-desu-ga-nani-ka-the-third-informal-conference-%e2%91%a0/',
            'title': "Kumo desu ga, Nani ka? The Third Informal Conference ①"},
        {
            'href': r'http://raisingthedead.ninja/2016/11/01/kumo-desu-ga-nani-ka-the-third-informal-conference-%e2%91%a1/',
            'title': "Kumo desu ga, Nani ka? The Third Informal Conference ②"},
        {'href': r'http://raisingthedead.ninja/2016/11/01/kumo-desu-ga-nani-ka-ss-halloween/',
         'title': "Kumo desu ga, Nani ka? SS &#8211; Halloween"},
        {'href': r'http://raisingthedead.ninja/2016/11/03/kumo-desu-ga-nani-ka-angry-oni/',
         'title': "Kumo desu ga, Nani ka? Angry Oni"},
        {'href': r'http://raisingthedead.ninja/2016/11/06/kumo-desu-ga-nani-ka-insane-oni/',
         'title': "Kumo desu ga, Nani ka? Insane Oni"},
        {'href': r'http://raisingthedead.ninja/2016/11/07/kumo-desu-ga-nani-ka-tipsy/',
         'title': "Kumo desu ga, Nani ka? Tipsy"},
        {'href': r'http://raisingthedead.ninja/2016/11/12/kumo-desu-ga-nani-ka-blood-35/',
         'title': "Kumo desu ga, Nani ka? Blood 35"},
        {'href': r'http://raisingthedead.ninja/2016/11/14/kumo-desu-ga-nani-ka-oni-19/',
         'title': "Kumo desu ga, Nani ka? Oni 19"},
        {'href': r'http://raisingthedead.ninja/2016/11/15/kumo-desu-ga-nani-ka-284/',
         'title': "Kumo desu ga, Nani ka? 284"},
        {'href': r'http://raisingthedead.ninja/2016/12/13/kumo-desu-ga-nani-ka-ss-autumn-leaf-viewing/',
         'title': "Kumo desu ga, Nani ka? SS Autumn-leaf Viewing"},
        {'href': r'http://raisingthedead.ninja/2016/12/22/kumo-desu-ga-nani-ka-timeline/',
         'title': "Kumo desu ga, Nani ka? Timeline"},
        {'href': r'http://raisingthedead.ninja/2016/12/30/kumo-desu-ga-nani-ka-285/',
         'title': "Kumo desu ga, Nani ka? 285"},
        {'href': r'http://raisingthedead.ninja/2017/01/01/kumo-desu-ga-nani-ka-286/',
         'title': "Kumo desu ga, Nani ka? 286"},
        {'href': r'http://raisingthedead.ninja/2017/01/02/kumo-desu-ga-nani-ka-ss-new-years-eve-soba/',
         'title': "Kumo desu ga, Nani ka? SS &#8211; New Year&#8217;s Eve Soba"},
        {'href': r'http://raisingthedead.ninja/2017/01/13/kumo-desu-ga-nani-ka-287/',
         'title': "Kumo desu ga, Nani ka? 287"},
        {'href': r'http://raisingthedead.ninja/2017/01/15/kumo-desu-ga-nani-ka-288/',
         'title': "Kumo desu ga, Nani ka? 288"},
        {'href': r'http://raisingthedead.ninja/2017/02/19/kumo-desu-ga-nani-ka-ss-valentine/',
         'title': "Kumo desu ga, Nani ka? SS – Valentine"},
        {'href': r'http://raisingthedead.ninja/2017/02/20/kumo-desu-ga-nani-ka-289/',
         'title': "Kumo desu ga, Nani ka? 289"},
        {'href': r'http://raisingthedead.ninja/2017/02/21/kumo-desu-ga-nani-ka-290/',
         'title': "Kumo desu ga, Nani ka? 290"},
        {'href': r'http://raisingthedead.ninja/2017/02/22/kumo-desu-ga-nani-ka-291/',
         'title': "Kumo desu ga, Nani ka? 291 – Elf Village Battle ①"},
        {'href': r'http://raisingthedead.ninja/2017/02/22/kumo-desu-ga-nani-ka-292/',
         'title': "Kumo desu ga, Nani ka? 292 &#8211; Elf Village Battle ②"},
        {'href': r'http://raisingthedead.ninja/2017/02/24/kumo-desu-ga-nani-ka-293/',
         'title': "Kumo desu ga, Nani ka? 293 &#8211; Elf Village Battle ③"},
        {'href': r'http://raisingthedead.ninja/2017/02/26/kumo-desu-ga-nani-ka-294/',
         'title': "Kumo desu ga, Nani ka? 294 &#8211; Elf Village Battle ④"},
        {'href': r'http://raisingthedead.ninja/2017/02/27/kumo-desu-ga-nani-ka-295/',
         'title': "Kumo desu ga, Nani ka? 295 &#8211; Elf Village Battle ⑤"},
        {'href': r'http://raisingthedead.ninja/2017/02/27/elf-village-battle-%e2%91%a5/',
         'title': "Kumo desu ga, Nani ka? Elf Village Battle ⑥"},
        {'href': r'http://raisingthedead.ninja/2017/03/03/kumo-desu-ga-nani-ka-elf-village-battle-%e2%91%a6/',
         'title': "Kumo desu ga, Nani ka? Elf Village Battle ⑦"},
        {'href': r'http://raisingthedead.ninja/2017/03/08/kumo-desu-ga-nani-ka-296/',
         'title': "Kumo desu ga, Nani ka? 296 &#8211; Elf Village Battle ⑧"},
        {'href': r'http://raisingthedead.ninja/2017/03/09/kumo-desu-ga-nani-ka-297/',
         'title': "Kumo desu ga, Nani ka? 297 &#8211; Elf Village Battle ⑨"},
        {'href': r'http://raisingthedead.ninja/2017/03/10/kumo-desu-ga-nani-ka-298/',
         'title': "Kumo desu ga, Nani ka? 298 &#8211; Elf Village Battle ⑩"},
        {'href': r'http://raisingthedead.ninja/2017/03/12/kumo-desu-ga-nani-ka-299/',
         'title': "Kumo desu ga, Nani ka? 299 &#8211; Elf Village Battle ⑪"},
        {'href': r'http://raisingthedead.ninja/2017/03/13/kumo-desu-ga-nani-ka-300/',
         'title': "Kumo desu ga, Nani ka? 300"},
        {'href': r'http://raisingthedead.ninja/2017/03/18/kumo-desu-ga-nani-ka-the-dreaming-boy/',
         'title': "Kumo desu ga, Nani ka? The dreaming boy"},
        {'href': r'http://raisingthedead.ninja/2017/03/19/kumo-desu-ga-nani-ka-past-arc-%e2%91%a0/',
         'title': "Kumo desu ga, Nani ka? Past Arc ①"},
        {'href': r'http://raisingthedead.ninja/2017/05/19/kumo-desu-ga-nani-ka-past-arc-%e2%91%a1/',
         'title': "Kumo desu ga, Nani ka? Past Arc ②"},
        {'href': r'http://raisingthedead.ninja/2017/05/20/kumo-desu-ga-nani-ka-past-arc-%e2%91%a2/',
         'title': "Kumo desu ga, Nani ka? Past Arc ③"},
        {'href': r'http://raisingthedead.ninja/2017/05/21/kumo-desu-ga-nani-ka-past-arc-%e2%91%a3/',
         'title': "Kumo desu ga, Nani ka? Past Arc ④"},
        {'href': r'http://raisingthedead.ninja/2017/05/21/oshiete-d-sensei-lesson-2/',
         'title': "Oshiete D-sensei! Lesson 2"},
        {'href': r'http://raisingthedead.ninja/2017/05/22/kumo-desu-ga-nani-ka-past-arc-%e2%91%a4/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑤"},
        {'href': r'http://raisingthedead.ninja/2017/05/22/kumo-desu-ga-nani-ka-past-arc6/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑥"},
        {'href': r'http://raisingthedead.ninja/2017/05/24/kumo-desu-ga-nani-ka-past-arc-%e2%91%a6/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑦"},
        {'href': r'http://raisingthedead.ninja/2017/05/25/kumo-desu-ga-nani-ka-past-arc-%e2%91%a7/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑧"},
        {'href': r'http://raisingthedead.ninja/2017/05/27/kumo-desu-ga-nani-ka-past-arc-%e2%91%a8/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑨"},
        {'href': r'http://raisingthedead.ninja/2017/06/03/kumo-desu-ga-nani-ka-past-arc-%e2%91%a9/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑩"},
        {'href': r'http://raisingthedead.ninja/2017/06/14/kumo-desu-ga-nani-ka-past-arc-%e2%91%aa/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑪"},
        {'href': r'http://raisingthedead.ninja/2017/06/24/kumo-desu-ga-nani-ka-past-arc-%e2%91%ab/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑫"},
        {'href': r'http://raisingthedead.ninja/2017/08/09/kumo-desu-ga-nani-ka-past-arc-%e2%91%ac/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑬"},
        {'href': r'http://raisingthedead.ninja/2017/08/13/kumo-desu-ga-nani-ka-past-arc-%e2%91%ad/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑭"},
        {'href': r'http://raisingthedead.ninja/2017/08/14/kumo-desu-ga-nani-ka-past-arc-%e2%91%ae/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑮"},
        {'href': r'http://raisingthedead.ninja/2017/08/22/kumo-desu-ga-nani-ka-past-arc-%e2%91%af/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑯"},
        {'href': r'http://raisingthedead.ninja/2017/08/23/kumo-desu-ga-nani-ka-past-arc-%e2%91%b0/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑰"},
        {'href': r'http://raisingthedead.ninja/2017/08/27/kumo-desu-ga-nani-ka-past-arc-%e2%91%b1/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑱"},
        {'href': r'http://raisingthedead.ninja/2017/08/30/kumo-desu-ga-nani-ka-past-arc-%e2%91%b2/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑲"},
        {'href': r'http://raisingthedead.ninja/2017/09/01/kumo-desu-ga-nani-ka-past-arc-%e2%91%b3/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑳"},
        {'href': r'http://raisingthedead.ninja/2017/09/03/kumo-desu-ga-nani-ka-past-arc-%e3%89%91/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉑"},
        {'href': r'http://raisingthedead.ninja/2017/09/04/kumo-desu-ga-nani-ka-past-arc-%e3%89%92/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉒"},
        {'href': r'http://raisingthedead.ninja/2017/09/04/kumo-desu-ga-nani-ka-past-arc-%e3%89%93/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉓"},
        {'href': r'http://raisingthedead.ninja/2017/09/06/kumo-desu-ga-nani-ka-past-arc-%e3%89%94/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉔"},
        {'href': r'http://raisingthedead.ninja/2017/09/07/kumo-desu-ga-nani-ka-past-arc-%e3%89%95/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉕"},
        {'href': r'http://raisingthedead.ninja/2017/09/09/kumo-desu-ga-nani-ka-past-arc-%e3%89%96/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉖"},
        {'href': r'http://raisingthedead.ninja/2017/09/11/kumo-desu-ga-nani-ka-past-reflections-ariel/',
         'title': "Kumo desu ga, Nani ka? Past Reflections: Ariel"},
        {'href': r'http://raisingthedead.ninja/2017/09/12/kumo-desu-ga-nani-ka-past-reflections-gyurie/',
         'title': "Kumo desu ga, Nani ka? Past Reflections: Gyurie"},
        {'href': r'http://raisingthedead.ninja/2017/09/18/kumo-desu-ga-nani-ka-character-introduction-2/',
         'title': "Kumo desu ga, Nani ka? Character Introduction 2"},
        {'href': r'http://raisingthedead.ninja/2017/09/18/kumo-desu-ga-nani-ka-oshiete-d-sensei-lesson-3/',
         'title': "Kumo desu ga, Nani ka? Oshiete D-sensei! Lesson 3"},
        {'href': r'http://raisingthedead.ninja/2017/09/19/kumo-desu-ga-nani-ka-301/',
         'title': "Kumo desu ga, Nani ka? 301"},
        {'href': r'http://raisingthedead.ninja/2017/09/19/kumo-desu-ga-nani-ka-302/',
         'title': "Kumo desu ga, Nani ka? 302"},
        {'href': r'http://raisingthedead.ninja/2017/09/19/kumo-desu-ga-nani-ka-303/',
         'title': "Kumo desu ga, Nani ka? 303"},
        {'href': r'http://raisingthedead.ninja/2017/09/20/kumo-desu-ga-nani-ka-304/',
         'title': "Kumo desu ga, Nani ka? 304"},
        {'href': r'http://raisingthedead.ninja/2017/09/21/kumo-desu-ga-nani-ka-305/',
         'title': "Kumo desu ga, Nani ka? 305"},
        {'href': r'http://raisingthedead.ninja/2017/09/22/kumo-desu-ga-nani-ka-s30/',
         'title': "Kumo desu ga, Nani ka? S30"},
        {'href': r'http://raisingthedead.ninja/2017/09/23/kumo-desu-ga-nani-ka-306/',
         'title': "Kumo desu ga, Nani ka? 306"},
        {'href': r'http://raisingthedead.ninja/2017/09/24/kumo-desu-ga-nani-ka-307/',
         'title': "Kumo desu ga, Nani ka? 307"},
        {'href': r'http://raisingthedead.ninja/2017/09/28/kumo-desu-ga-nani-ka-308/',
         'title': "Kumo desu ga, Nani ka? 308"},
        {'href': r'http://raisingthedead.ninja/2017/09/30/kumo-desu-ga-nani-ka-309/',
         'title': "Kumo desu ga, Nani ka? 309"},
        {'href': r'http://raisingthedead.ninja/2017/10/04/kumo-desu-ga-nani-ka-310/',
         'title': "Kumo desu ga, Nani ka? 310"},
        {'href': r'http://raisingthedead.ninja/2017/10/15/kumo-desu-ga-nani-ka-s31/',
         'title': "Kumo desu ga, Nani ka? S31"},
        {'href': r'http://raisingthedead.ninja/2017/12/18/kumo-desu-ga-nani-ka-311/',
         'title': "Kumo desu ga, Nani ka? 311"},
        {'href': r'http://raisingthedead.ninja/2017/12/18/kumo-desu-ga-nani-ka-312/',
         'title': "Kumo desu ga, Nani ka? 312"},
        {'href': r'http://raisingthedead.ninja/2017/12/18/kumo-desu-ga-nani-ka-313/',
         'title': "Kumo desu ga, Nani ka? 313"},
        {'href': r'http://raisingthedead.ninja/2018/01/15/kumo-desu-ga-nani-ka-314/',
         'title': "Kumo desu ga, Nani ka? 314"},
        {'href': r'http://raisingthedead.ninja/2018/01/16/kumo-desu-ga-nani-ka-315/',
         'title': "Kumo desu ga, Nani ka? 315"},
        {'href': r'http://raisingthedead.ninja/2018/02/04/kumo-desu-ga-nani-ka-s32/',
         'title': "Kumo desu ga, Nani ka? S32"},
        {'href': r'http://raisingthedead.ninja/2018/02/04/kumo-desu-ga-nani-ka-oshiete-d-sensei-lesson-4/',
         'title': "Kumo desu ga, Nani ka? Oshiete D-sensei! Lesson 4"},
        {'href': r'http://raisingthedead.ninja/2018/02/05/kumo-desu-ga-nani-ka-316/',
         'title': "Kumo desu ga, Nani ka? 316"}
    ]
    out = r'C:\Users\Maoserr\Desktop\Out'
    out_htmls = []
    for i in range(0,len(files)-1):
        base_name = os.path.split(os.path.split(files[i]['href'])[0])[1]
        curr_html = os.path.join(out,str(i)+"_"+base_name+".html")
        out_html = os.path.join(out,str(i)+"_"+base_name+"_out.html")
        print("Page "+str(i))
        out_htmls.append(out_html)
        if os.path.exists(curr_html):
            with open(curr_html,'rb') as f:
                txt = f.read().decode("utf-8")
        else:
            txt = downloadFile(files[i]['href'])
        soup = BeautifulSoup(txt, 'html.parser')
        body=soup.find_all('div',class_='entry-content')
        ps = body[0].find_all('p')
        with open(out_html,'wb') as f:
            for p in ps:
                if(p.find_all('div',class_="saboxplugin-wrap")):
                    continue
                if(p.find_all('iframe')):
                    continue
                f.write(str(p).encode("utf-8")+b'\n')
    book = epub.EpubBook()

    # set metadata
    book.set_identifier('id121234')
    book.set_title('Kumo Desu Ga (RAD)')
    book.set_language('en')

    book.add_author('Author')

    spine = ['nav']
    for i in range(0,len(out_htmls)-1):
        base_name = os.path.splitext(os.path.basename(out_htmls[i]))[0].replace("%","_")
        # create chapter
        c1 = epub.EpubHtml(title=base_name, file_name=base_name+".xhtml")
        with open(out_htmls[i],'rb') as f:
            c1.content=f.read()
        spine.append(c1)

        # add chapter
        book.add_item(c1)

    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = spine
    # write to the file
    epub.write_epub(os.path.join(out,"Kumo_RAD.epub"), book, {})

raisedead()