import os
import requests
import html

from bs4 import BeautifulSoup
from ebooklib import epub
from PIL import Image,ImageDraw,ImageFont
from io import BytesIO


def downloadFile(URL=None):
    headers = {
        'USER-AGENT': 'Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405'}

    data = requests.get(URL, headers=headers).content
    text = data.decode('utf-8')  # a `str`; this step can't be used if data is binary
    return text

def tubosquid():
    files = [
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desuga-nanika-chapter-1.html",
         'title': "01 Prologue"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desuga-nanika-chapter-2.html",
         'title': "02 Looks like I'm a monster"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desuga-nanika-chapter-3.html",
         'title': "03 There was a time when I thought that 'Appraisal' was a cheat skill"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desuga-nanika-chapter-4.html",
         'title': "04 Exploring a dungeon for the first time"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ga-nani-ka-chapter-5.html",
         'title': "05 Chapter of a new home"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ga-nani-ka-chapter-6.html",
         'title': "06&nbsp;I didn't regret after munching it"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ga-nani-ka-chapter-7.html",
         'title': "07&nbsp;24 hours vacation throughout the year"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ga-nani-ka-chapter-8.html",
         'title': "08&nbsp;A spider without intelligence is just a normal spider"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ga-nani-ka-chapter-9.html",
         'title': "09 Skill verification"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ga-nani-ka-chapter-10.html",
         'title': "10&nbsp;Level Up!"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ka-nani-ga-chapter-s1.html",
         'title': "S1 The day when the daily life ended"},
        {'href': "http://turb0translation.blogspot.com/2015/06/kumo-desu-ga-nani-ka-chapter-11.html",
         'title': "11 I~to maki maki i~to maki maki&#9834;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-12.html",
         'title': "12 A moving reunion(lol)"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-13.html",
         'title': "13 I received a disgraceful 'title'"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-14.html",
         'title': "14 Chapter of reconstruction"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-15.html",
         'title': "15 The time I lose my paradise"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-16.html",
         'title': "16 Leaving the nest"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-17.html",
         'title': "17 I use a dirty trick fair and square head-on"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-18.html",
         'title': "18 Complete recovery after staying at the inn is only in game"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-19.html",
         'title': "19 It's not a big deal if it does not hit!"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-20.html",
         'title': "20 I am a spider, currently behind you"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s2.html",
         'title': "S2 The fourth prince"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-21.html",
         'title': "21 HP MP SP"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-22.html",
         'title': "22 Spider thread experiments"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-23.html",
         'title': "23 I'm sorry that I got carried away. Please forgive me!"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-24.html",
         'title': "24 Weak"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-25.html",
         'title': "25 Delicious snake"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-q-1.html", 'title': "Q&amp;A 1"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-26.html",
         'title': "26 De-hikki plan"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-27.html",
         'title': "27 I'm going to evolve!"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-28.html",
         'title': "28 Eat eat eat"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-29.html",
         'title': "29 The things that I need to do are still the same even if I evolve"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-30.html",
         'title': "30 Let's acquire a new skill!"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s3.html",
         'title': "S3 Fantasy"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-q-2.html", 'title': "Q&amp;A 2"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-31.html",
         'title': "31&nbsp;I gained new skills"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-32.html",
         'title': "32 Growth period?"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-33.html",
         'title': "33 The seriousness of Appraisal-san"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-34.html",
         'title': "34 Sequel&#12539;Growth period"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-35.html",
         'title': "35 Therefore, don't get carried away that much(ry"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s4.html",
         'title': "S4 Magic"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-q-3.html", 'title': "Q&amp;A 3"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-36.html",
         'title': "36 Desperate situation"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-39.html",
         'title': "39 Spider vs Bee &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-40.html",
         'title': "40 Spider vs Bee &#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s5.html",
         'title': "S5 Appraisal stone"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-41.html",
         'title': "41 I achieved the desired level up!"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-42.html",
         'title': "42 Spider vs Bee &#9315;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-43.html",
         'title': "43 Spider vs Earth Dragon.........Eh?"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-44.html",
         'title': "44 Escape from despair"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-45.html",
         'title': "45 Elro Great Labyrinth Lower Layer"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s6.html",
         'title': "S6 Status"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-46.html",
         'title': "46 Survival of the fittest, or so I thought, but...."},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-47.html",
         'title': "47 Poison poison"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-48.html",
         'title': "48 Forked, road?"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-49.html",
         'title': "49 Appraisal-san, you were a cheat after all"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-50.html",
         'title': "50 Mahou Shoujo Magical Kumoko&#9734;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s7.html",
         'title': "S7 Duke's daughter"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-extra.html",
         'title': "Extra Bestiary&#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-51.html",
         'title': "51 Isn't it great to know the enemy's strength?"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-52.html",
         'title': "52 Threadness and sadness and heartening and"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-53.html",
         'title': "53 I have become stronger even if it's a little"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-54.html",
         'title': "54 Quiet sleep great strategy!"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-55.html",
         'title': "55 The defensive battle of 100 meters above ground &#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-q-5.html", 'title': "Q&amp;A 5"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s8.html",
         'title': "S8 Skill encyclopedia"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-56.html",
         'title': "56 The defensive battle of 100 meters above ground &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-57.html",
         'title': "57 The defensive battle of 100 meters above ground &#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-58.html",
         'title': "58 The defensive battle of 100 meters above ground &#9315;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-59.html",
         'title': "59 The defensive battle of 100 meters above ground &#9316;"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-60.html",
         'title': "60 The defensive battle of 100 meters above ground End"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-s9.html",
         'title': "S9 Skill point"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-61.html",
         'title': "61 I'm going to evolve! Part 2"},
        {'href': "http://turb0translation.blogspot.com/2015/07/kumo-desu-ga-nani-ka-chapter-62.html",
         'title': "62 Poison spider"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-63.html",
         'title': "63 Appraisal-san, no, Appraisal-sama!"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-64.html",
         'title': "64 Appraisal-sama is really an intelligent person"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-65.html",
         'title': "65 Pride"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s10.html",
         'title': "S10 The second prince"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-66.html",
         'title': "66 Skill rush"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-67.html",
         'title': "67 A formidable enemy appears! The name is Detection!"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-68.html",
         'title': "68 The end of the lower layer"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-q-6.html", 'title': "Q&amp;A 6"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-69.html",
         'title': "69 Elro Great Labyrinth Middle Layer"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-70.html",
         'title': "70 Training part"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-y1.html",
         'title': "Y1 Hero and the king"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-71.html",
         'title': "71 Leveling"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-72.html",
         'title': "72 Leveling result"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-73.html",
         'title': "73 Death flag suddenly"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-74.html",
         'title': "74 Middle layer capture starts"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-75.html",
         'title': "75 It's good to do my part by myself, but there are times you feel frustrated when it's done by someone else, right?"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s11.html",
         'title': "S11 Elf girl"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-76.html",
         'title': "76 Let's become even hotter!"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-q-7.html", 'title': "Q&amp;A 7"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-77.html",
         'title': "77 Unlucky 7"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-78.html",
         'title': "78 ... It's an amazing skill."},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-79.html",
         'title': "79 How's a spider who's full of dangerous 'title's?"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-80.html",
         'title': "80 Spider vs Fire Drake &#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s12.html",
         'title': "S12 Academy"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-q-8.html", 'title': "Q&amp;A 8"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-81.html",
         'title': "81 Spider vs Fire Drake &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-82.html",
         'title': "82 Spider vs Fire Drake &#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-83.html",
         'title': "83 Spider vs Fire Drake &#9315;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-84.html",
         'title': "84 Spider vs Fire Drake &#9316;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-85.html",
         'title': "85 Spider vs Fire Drake End"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-extra-2.html",
         'title': "Extra Bestiary &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s13.html",
         'title': "S13 Saint and Sword Emperor"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-86.html",
         'title': "86 Dance of victory"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-87.html",
         'title': "87 I'm going to evolve! Part 3"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-88.html",
         'title': "88 Zoa Ere"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-89.html",
         'title': "89 Changes due to evolution"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-90.html",
         'title': "90 Patience"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-k1.html",
         'title': "K1 Pessimistic Duke's daughter"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-q-9.html", 'title': "Q&amp;A 9"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-91.html",
         'title': "91 Detection-san, you were a formidable enemy"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-92.html",
         'title': "92 Once again, I have cut a worthless object"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-93.html",
         'title': "93 The thing that extends over the layer"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-94.html",
         'title': "94 The top needs the top, so let's aim at more top"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-95.html",
         'title': "95 Higher rank species"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s14.html",
         'title': "S14 Academy life"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-96.html",
         'title': "96 I think, therefore I am. I move, therefore I am. I am me and me, therefore it is me."},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-97.html",
         'title': "97 The eight passes"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-98.html",
         'title': "98 Look at my eyes!"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-99.html",
         'title': "99 Because that guy is an idiot, I must get a grip on myself"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-100.html",
         'title': "100 Oh? Appraisal-sama's state....?"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s15.html",
         'title': "S15 Ruler class"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-101.html",
         'title': "101 Wisdom"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-102.html",
         'title': "102 Wisdom-sama is amazing"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-103.html",
         'title': "103 Magical Kumoko&#9734;Returns"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-104.html",
         'title': "104 Magic Equipped Spider-type Versatile Warrior"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-q-10.html", 'title': "Q&amp;A 10"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-105.html",
         'title': "105 Does a Hikki dream of going out?"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s16.html",
         'title': "S16 The unrest that creeps to the peaceful shadow"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-106.html",
         'title': "106 Eel again"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-107.html",
         'title': "107 Master of the flame sea &#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-108.html",
         'title': "108 Master of the flame sea &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-109.html",
         'title': "109 Fear Bringer"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-110.html",
         'title': "110 The thing acquired after defeating the Fire Drake"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-b1.html",
         'title': "B1 The Demon King's close aide lets out a sigh at the conference"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-y2.html",
         'title': "Y2 And the war began"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-human-demon-great_67.html",
         'title': "Human-Demon Great War &#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-human-demon-great.html",
         'title': "Human-Demon Great War &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-human-demon-great_20.html",
         'title': "Human-Demon Great War &#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-human-demon-great_21.html",
         'title': "Human-Demon Great War &#9315;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-human-demon-great_97.html",
         'title': "Human-Demon Great War &#9316;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s17.html",
         'title': "S17 Voice informing the collapse"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-human-demon-great_81.html",
         'title': "Human-Demon Great War Secret"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-111.html",
         'title': "111 Delicious cuisine"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-112.html",
         'title': "112 Monsters that change into metal"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-113.html",
         'title': "113 Spider vs Fire Dragon &#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-114.html",
         'title': "114 Spider vs Fire Dragon &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-115.html",
         'title': "115 Spider vs Fire Dragon &#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-s18.html", 'title': "S18 New Hero"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-116.html",
         'title': "116 Spider vs Fire Dragon &#9315;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-117.html",
         'title': "117 Dragon Killer"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-118.html",
         'title': "118 The meaning of killing a Dragon"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-119.html",
         'title': "119 Beam from the eyes! I won't do it though"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-120.html",
         'title': "120 Administrator"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s19.html",
         'title': "S19 Julius"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-extra-3.html",
         'title': "Extra Bestiary &#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-121.html",
         'title': "121 Let's forget about it quickly"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-122.html",
         'title': "122 Flying flying flying"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-123.html",
         'title': "123 I obtained the Dragon Power! Uhahahaha!"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-124.html",
         'title': "124 Upper layer, I have returned!"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-125.html",
         'title': "125 Deep fried!"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-s20.html",
         'title': "S20 Fall"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-126.html",
         'title': "126 Real tag&#12288;The 'it' is a spider"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-elro-great_28.html",
         'title': "Elro Great Labyrinth Abnormality Investigation Team &#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-elro-great.html",
         'title': "Elro Great Labyrinth Abnormality Investigation Team &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-elro-great_68.html",
         'title': "Elro Great Labyrinth Abnormality Investigation Team &#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-127.html",
         'title': "127 Show me the possibility that a person has"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-128.html",
         'title': "128 Mercy is not for others"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-129.html",
         'title': "129 I'm going to evolve! Part 4"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-130.html",
         'title': "130 Taboo"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-k2.html",
         'title': "K2 The last obstinacy of a man"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-b2.html",
         'title': "B2 Maou-sama is dismayed"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-131.html",
         'title': "131 I lost"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-132.html",
         'title': "132 Earth Dragon Kaguna capture preparations"},
        {'href': "http://turb0translation.blogspot.com/2015/08/kumo-desu-ga-nani-ka-chapter-133.html",
         'title': "133 No.1 of hardness, No.2 of speed"},
        {'href': "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ga-chapter-134.html",
         'title': "134 Spider's natural enemy"},
        {'href': "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ka-chapter-135.html",
         'title': "135 Spider vs Spider &#9312;"},
        {'href': "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ka-chapter-s21.html",
         'title': "S21 The world's truth"},
        {'href': "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ka-chapter-136.html",
         'title': "136 Spider vs Spider &#9313;"},
        {'href': "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ka-chapter-137.html",
         'title': "137 Spider vs Spider&nbsp;&#9314;"},
        {'href': "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ka-chapter-138.html",
         'title': "138&nbsp;Spider vs Earth Dragon Alaba &#9312;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-139.html",
         'title': "139 Spider vs Earth Dragon Alaba &#9313;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-140.html",
         'title': "140 Spider vs Earth Dragon Alaba &#9314;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-141.html",
         'title': "141 Spider vs Earth Dragon Alaba&nbsp;&#9315;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-142.html",
         'title': "142 Spider vs Earth Dragon Alaba&nbsp;&#9316;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-143.html",
         'title': "143 Spider vs Earth Dragon Alaba&nbsp;&#9317;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-144.html",
         'title': "144 Spider vs Earth Dragon Alaba&nbsp;&#9318;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-145.html",
         'title': "145 The sinking earth"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-royal-capital.html",
         'title': "The royal capital battle &#9312;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-royal-capital_5.html",
         'title': "The royal capital battle&nbsp;&#9313;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-royal-capital_87.html",
         'title': "The royal capital battle&nbsp;&#9314;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-146.html",
         'title': "146 I feel sick"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths.html",
         'title': "The labyrinth's nightmare &#9312;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths_6.html",
         'title': "The labyrinth's nightmare&nbsp;&#9313;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths_7.html",
         'title': "The labyrinth's nightmare&nbsp;&#9314;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-labyrinths_63.html",
         'title': "The labyrinth's nightmare&nbsp;&#9315;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-147.html",
         'title': "147 So, this is the possibility that a person has"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-148.html",
         'title': "148&nbsp;I'm going to evolve! Part 5"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-149.html",
         'title': "149 Hello, this is the Evil God"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-150.html",
         'title': "150 You're just the Hero and the Demon King, don't get cocky!"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s22.html",
         'title': "S22 To the Elf Village"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-151.html",
         'title': "151 Outside"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-152.html",
         'title': "152 The spider traveling alone aimlessly"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-153.html",
         'title': "153 Conversation with Kuro"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-154.html",
         'title': "154 Mountain foods"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-155.html",
         'title': "155 The reason to climb the mountain is because ingredients are there"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s23.html",
         'title': "S23 Entering the Elro Great Labyrinth"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-156.html",
         'title': "156 It's the sea!"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-157.html",
         'title': "157 Sea fishing"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-158.html",
         'title': "158 When I thought that it was a fishing village, it was a farm village"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-159.html",
         'title': "159 Sneak thief &#65310; Bandits"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-160.html",
         'title': "160 Vampire Princess"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s24.html",
         'title': "S24 The Elro Great Labyrinth capture &#9312;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-161.html",
         'title': "161 Town"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-162.html",
         'title': "162 Dear Sir or Madam, I moved"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-163.html",
         'title': "163 Worship me, praise me"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-164.html",
         'title': "164 The picky savior"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-165.html",
         'title': "165 It's a curse"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s25.html",
         'title': "S25 The Elro Great Labyrinth capture &#9313;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-166.html",
         'title': "166 Mother eating"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-167.html",
         'title': "167 Spider of the rebellion"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-168.html",
         'title': "168 Write the things I want to memorize in the notebook and eat it like that"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-169.html",
         'title': "169 No more tributes"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-170.html",
         'title': "170 Demon King Ariel"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s26.html",
         'title': "S26 The Elro Great Labyrinth capture &#9314;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-divine-word.html",
         'title': "The Divine Word Religion and the Goddess Religion"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-171.html",
         'title': "171 Since when were you under the impression that I can't escape from the Great Demon King?"},
        {'href': "http://turb0translation.blogspot.com/2015/09/kumo-desu-ga-nani-ka-chapter-172.html",
         'title': "172 I let the children to pay the tribute"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-173.html",
         'title': "173 Sponger"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-174.html",
         'title': "174 Apprenticeship applicant"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-searching-for.html",
         'title': "Searching for master 3 thousand miles"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-magician.html",
         'title': "Magician, apprenticeship"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-175.html",
         'title': "175 Revival!"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s27.html",
         'title': "S27 The Remnants of the Nightmare"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-176.html",
         'title': "176 Spare body talks"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-177.html",
         'title': "177 Inside the Demon King"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-178.html",
         'title': "178 Demon King vs Earth Dragon"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-179.html",
         'title': "179 Demon King of Gluttony"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-180.html",
         'title': "180 Spare body moves"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s28.html",
         'title': "S28 The Elro Great Labyrinth escape"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-181.html",
         'title': "181 It becomes something terrible"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-182.html",
         'title': "182 Battlefield inspection"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-183.html",
         'title': "183 People are trash"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-184.html",
         'title': "184 Now, pray to God"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-185.html",
         'title': "185 The small Hero"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-s29.html",
         'title': "S29 Offer"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-186.html",
         'title': "186 Arachne"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-187.html",
         'title': "187 Communication ability"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-188.html",
         'title': "188 I'm hungry"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-189.html",
         'title': "189 Body function verification"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-190.html",
         'title': "190 Cuisine"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-elf-village-1.html",
         'title': "Elf Village &#9312;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-elf-village-2.html",
         'title': "Elf Village &#9313;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-elf-village-3.html",
         'title': "Elf Village &#9314;"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-because-i-am.html",
         'title': "Because I am a teacher"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-191.html",
         'title': "191 Tsuchigumo"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-192.html",
         'title': "192 Sea fishing part 2"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-193.html",
         'title': "193 The Administrator complains"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-194.html",
         'title': "194 The Demon King talks"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-195.html",
         'title': "195 Changes"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-before-war.html",
         'title': "Before the war"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-196.html",
         'title': "196 Rather than the spider, it's the ant"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-197.html",
         'title': "197 The treasure is buried underground?"},
        {'href': "http://turb0translation.blogspot.my/2015/09/kumo-desu-ga-nani-ka-chapter-198.html",
         'title': "198 Underground ruins"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-199.html",
         'title': "199 Robot army"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-200.html",
         'title': "200 Loot"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle.html",
         'title': "Elf Village Battle &#9312;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_2.html",
         'title': "Elf Village Battle &#9313;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_40.html",
         'title': "Elf Village Battle &#9314;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_30.html",
         'title': "Elf Village Battle &#9315;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_3.html",
         'title': "Elf Village Battle &#9316;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_18.html",
         'title': "Elf Village Battle &#9317;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_45.html",
         'title': "Elf Village Battle &#9318;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_99.html",
         'title': "Elf Village Battle &#9319;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_4.html",
         'title': "Elf Village Battle &#9320;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_79.html",
         'title': "Elf Village Battle &#9321;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-elf-village-battle_78.html",
         'title': "Elf Village Battle &#9322;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-201.html",
         'title': "201 The Demon King and the Queen"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-202.html",
         'title': "202 God"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-203.html",
         'title': "203 Uninhabited area"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-204.html",
         'title': "204 Easy"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-205.html",
         'title': "205 The Demon King who's accompanied by God"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-1.html",
         'title': "Oni 1 Sasajima Kyouya"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-character.html",
         'title': "Character introduction"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-206.html",
         'title': "206 Black and white"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-207.html",
         'title': "207 Start"},
        {'href': "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-blood-1.html",
         'title': "Blood 1 Negishi Akiko"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-2.html",
         'title': "Blood 2 Redo"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-3.html",
         'title': "Blood 3 Encounter with the spider"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-2.html",
         'title': "Oni 2 Goblin"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-4.html",
         'title': "Blood 4 Countdown to despair"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-5.html",
         'title': "Blood 5 Survival strategy"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-6.html",
         'title': "Blood 6 Sudden change"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-7.html",
         'title': "Blood 7 War"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-8.html",
         'title': "Blood 8 Decision"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-3.html",
         'title': "Oni 3 Weapon creation"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-9.html",
         'title': "Blood 9 Attendant"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-10.html",
         'title': "Blood 10 Strange woman and dangerous woman"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-208.html",
         'title': "208 The standard of the fantasy world and the first encounter"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-209.html",
         'title': "209 Vampire attendant conciliatory operation"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-210.html",
         'title': "210 Vampire master conciliatory operation"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-4.html",
         'title': "Oni 4 Naming"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-11.html",
         'title': "Blood 11 What should I do if my classmate becomes a monster when reincarnated?"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-12.html",
         'title': "Blood 12 The Divine Word Religion and the Elves"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-13.html",
         'title': "Blood 13 Envy"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-14.html",
         'title': "Blood 14 The lie and the truth"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-15.html",
         'title': "Blood 15 Announcing the little girl abuse warning officially"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-5.html",
         'title': "Oni 5 The trampled one"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-16.html",
         'title': "Blood 16 Along the way"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-17.html",
         'title': "Blood 17 The Demon King of money"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-18.html",
         'title': "Blood 18 Abnormal Condition &#12300;Drunkard&#12301;"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-211.html",
         'title': "211 Vampire training plan"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-chapter-212.html",
         'title': "212 Maou-sama's 3 hours cooking"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-6.html", 'title': "Oni 6 Slave"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-19.html",
         'title': "Blood 19 Both the inside and the outside are dangerous"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-20.html",
         'title': "Blood 20 Master is a brute"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-21.html",
         'title': "Blood 21 Three years"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-regular-reports-of.html",
         'title': "The regular reports of the Demon King and the Administrator"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-pope-and.html",
         'title': "The Pope and the Administrator"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-7.html",
         'title': "Oni 7 Illusion Weapon Creation"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-22.html",
         'title': "Blood 22 Demons......."},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-23.html",
         'title': "Blood 23 It seems that I have to go to the magic academy if I'm reincarnated"},
        {'href': "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-blood-24.html",
         'title': "Blood 24 Enrollment"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-25.html",
         'title': "Blood 25 Although I who have encountered an engagement annulment event is like a heroine, because I don't have the memory of being bullied, what should I do?"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-blood-26.html",
         'title': "Blood 26 Blood of Oni"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-8.html", 'title': "Oni 8 Wrath"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-revolving-lantern.html",
         'title': "The revolving lantern of the summoner"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-rumor-of-adventurer.html",
         'title': "The rumor of the adventurer"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-adventurers-vs-ogre.html",
         'title': "Adventurers vs Ogre"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-empire-knights-vs.html",
         'title': "Empire knights vs Ogre"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-old-man2-vs-ogre.html",
         'title': "Old man&#215;2 vs Ogre"},
        {'href': "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-oni-9.html",
         'title': "Oni 9 Calmly"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-sword-king-and.html",
         'title': "The Sword King and the magician"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-pope-and-ninja.html",
         'title': "The Pope and the Ninja"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-country-of.html",
         'title': "The country of the interstice"},
        {'href': "http://turb0translation.blogspot.com/2015/10/kumo-desu-ga-nani-ka-previous-sword.html",
         'title': "The previous Sword Emperor"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-sword-god-vs-ogre.html",
         'title': "Sword God vs Ogre"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-10.html",
         'title': "Oni 10 Emptiness"},
        {'href': "http://turb0translation.blogspot.my/2015/10/kumo-desu-ga-nani-ka-oni-vs-oni-1.html",
         'title': "Oni vs Oni &#9312;"},
        {'href': "http://turb0translation.blogspot.my/2015/11/kumo-desu-ga-nani-ka-oni-vs-oni-2.html",
         'title': "Oni vs Oni &#9313;"}
    ]

    out = r'Out\Turbo'
    out_htmls = []
    out_titles = []
    for i in range(0,len(files)-1):
        base_name = os.path.splitext(os.path.basename(files[i]['href']))[0]
        curr_html = os.path.join(out,str(i)+base_name+".html")
        print("Page "+str(i))
        out_htmls.append(curr_html)
        out_titles.append(files[i]['title'])
        if os.path.exists(curr_html):
            continue
        txt = downloadFile(files[i]['href'])
        soup = BeautifulSoup(txt, 'html.parser')
        body=soup.find_all('div',class_='post-body')
        with open(curr_html,'wb') as f:
            f.write(body[0].encode("utf-8"))

    book = epub.EpubBook()

    # set metadata
    book.set_identifier('id1234562134')
    book.set_title('Kumo Desu Ga? Nani ka? (Chap 1-214)')
    book.set_language('en')

    book.add_author('Baba Okina')
    book.set_cover("image.jpg", open(r'bookcover\kumoturbo.jpeg', 'rb').read())

    spine = ['nav']
    toc = []
    for i in range(0,len(out_htmls)-1):
        base_name = os.path.splitext(os.path.basename(out_htmls[i]))[0]
        # create chapter
        c1 = epub.EpubHtml(title=html.unescape(out_titles[i]), file_name=base_name+".xhtml")
        with open(out_htmls[i],'rb') as f:
            c1.content=f.read()
        spine.append(c1)
        toc.append(c1)

        # add chapter
        book.add_item(c1)

    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = spine
    book.toc = toc
    # write to the file
    epub.write_epub(os.path.join(out,"Kumo_Tubo.epub"), book, {})

def raisedead():
    files = [
        {'href': r'http://raisingthedead.ninja/2015/11/09/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a2/',
         'title': "Kumo Desu Ga, Nani Ka? Oni vs Oni ③"},
        {'href': r'http://raisingthedead.ninja/2015/11/11/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a3/',
         'title': "Kumo Desu Ga, Nani Ka? Oni Vs Oni ④"},
        {'href': r'http://raisingthedead.ninja/2015/11/11/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a4/',
         'title': "Kumo Desu Ga, Nani Ka? Oni vs Oni ⑤"},
        {'href': r'http://raisingthedead.ninja/2015/11/11/kumo-desu-ga-nani-ka-oni-vs-oni-%e2%91%a5/',
         'title': "Kumo Desu Ga, Nani Ka? Oni VS Oni ⑥"},
        {'href': r'http://raisingthedead.ninja/2015/11/19/kumo-desu-ga-nani-ka-213/',
         'title': "Kumo Desu Ga, Nani Ka? 213"},
        {'href': r'http://raisingthedead.ninja/2015/11/20/kumo-desu-ga-nani-ka-214/',
         'title': "Kumo Desu Ga, Nani Ka? 214"},
        {'href': r'http://raisingthedead.ninja/2015/12/01/kumo-desu-ga-nani-ka-215/',
         'title': "Kumo Desu Ga, Nani Ka? 215"},
        {'href': r'http://raisingthedead.ninja/2015/12/01/kumo-desu-ga-nani-ka-216/',
         'title': "Kumo Desu Ga, Nani Ka? 216"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-217/',
         'title': "Kumo desu ga, Nani ka? 217"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-218/',
         'title': "Kumo desu ga, Nani ka? 218"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-219/',
         'title': "Kumo desu ga, Nani ka? 219"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-220/',
         'title': "Kumo desu ga, Nani ka? 220"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/oshiete-d-sensei-lesson-1/',
         'title': "Oshiete D-sensei! Lesson 1"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-221/',
         'title': "Kumo desu ga, Nani ka? 221"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-222/',
         'title': "Kumo desu ga, Nani ka? 222"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-223/',
         'title': "Kumo desu ga, Nani ka? 223"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-224/',
         'title': "Kumo desu ga, Nani ka? 224"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-225/',
         'title': "Kumo desu ga, Nani ka? 225"},
        {'href': r'http://raisingthedead.ninja/2015/12/24/kumo-desu-ga-nani-ka-226/',
         'title': "Kumo desu ga, Nani ka? 226"},
        {'href': r'http://raisingthedead.ninja/2016/01/27/kumo-desu-ga-nani-ka-227/',
         'title': "Kumo desu ga, Nani ka? 227"},
        {'href': r'http://raisingthedead.ninja/2016/01/27/kumo-desu-ga-nani-ka-228/',
         'title': "Kumo desu ga, Nani ka? 228"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-229/',
         'title': "Kumo desu ga, Nani ka? 229"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-230/',
         'title': "Kumo desu ga, Nani ka? 230"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-231/',
         'title': "Kumo desu ga, Nani ka? 231"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-232/',
         'title': "Kumo desu ga, Nani ka? 232"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-233/',
         'title': "Kumo desu ga, Nani ka? 233"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-234/',
         'title': "Kumo desu ga, Nani ka? 234"},
        {'href': r'http://raisingthedead.ninja/2016/01/28/kumo-desu-ga-nani-ka-235/',
         'title': "Kumo desu ga, Nani ka? 235"},
        {'href': r'http://raisingthedead.ninja/2016/01/29/kumo-desu-ga-nani-ka-236/',
         'title': "Kumo desu ga, Nani ka? 236"},
        {'href': r'http://raisingthedead.ninja/2016/01/30/kumo-desu-ga-nani-ka-237/',
         'title': "Kumo desu ga, Nani ka? 237"},
        {'href': r'http://raisingthedead.ninja/2016/01/31/6231/', 'title': "Kumo desu ga, Nani ka? 238"},
        {'href': r'http://raisingthedead.ninja/2016/02/01/kumo-desu-ga-nani-ka-239/',
         'title': "Kumo desu ga, Nani ka? 239"},
        {'href': r'http://raisingthedead.ninja/2016/02/02/kumo-desu-ga-nani-ka-240/',
         'title': "Kumo desu ga, Nani ka? 240"},
        {'href': r'http://raisingthedead.ninja/2016/02/05/the-commanders-bad-day/',
         'title': "Kumo Desu ga, Nani ka? The Commander’s Bad Day"},
        {'href': r'http://raisingthedead.ninja/2016/02/06/kumo-desu-ga-nani-ka-ss-christmas/',
         'title': "Kumo Desu ga, Nani ka? SS &#8211; Christmas"},
        {'href': r'http://raisingthedead.ninja/2016/02/07/kumo-desu-ga-nani-ka-241/',
         'title': "Kumo desu ga, Nani ka? 241"},
        {'href': r'http://raisingthedead.ninja/2016/02/08/kumo-desu-ga-nani-ka-242/',
         'title': "Kumo desu ga, Nani ka? 242"},
        {'href': r'http://raisingthedead.ninja/2016/02/09/kumo-desu-ga-nani-ka-243/',
         'title': "Kumo desu ga, Nani ka? 243"},
        {'href': r'http://raisingthedead.ninja/2016/02/10/kumo-desu-ga-nani-ka-244/',
         'title': "Kumo desu ga, Nani ka? 244"},
        {'href': r'http://raisingthedead.ninja/2016/02/11/kumo-desu-ga-nani-ka-245/',
         'title': "Kumo desu ga, Nani ka? 245"},
        {'href': r'http://raisingthedead.ninja/2016/02/12/kumo-desu-ga-nani-ka-246/',
         'title': "Kumo desu ga, Nani ka? 246"},
        {'href': r'http://raisingthedead.ninja/2016/02/14/kumo-desu-ga-nani-ka-247/',
         'title': "Kumo desu ga, Nani ka? 247"},
        {'href': r'http://raisingthedead.ninja/2016/02/15/kumo-desu-ga-nani-ka-248/',
         'title': "Kumo desu ga, Nani ka? 248"},
        {'href': r'http://raisingthedead.ninja/2016/02/16/kumo-desu-ga-nani-ka-249/',
         'title': "Kumo desu ga, Nani ka? 249"},
        {'href': r'http://raisingthedead.ninja/2016/02/17/kumo-desu-ga-nani-ka-250/',
         'title': "Kumo desu ga, Nani ka? 250"},
        {'href': r'http://raisingthedead.ninja/2016/02/18/kumo-desu-ga-nani-ka-251/',
         'title': "Kumo desu ga, Nani ka? 251"},
        {'href': r'http://raisingthedead.ninja/2016/02/19/kumo-desu-ga-nani-ka-252/',
         'title': "Kumo desu ga, Nani ka? 252"},
        {'href': r'http://raisingthedead.ninja/2016/02/20/kumo-desu-ga-nani-ka-253/',
         'title': "Kumo desu ga, Nani ka? 253"},
        {'href': r'http://raisingthedead.ninja/2016/02/21/kumo-desu-ga-nani-ka-254/',
         'title': "Kumo desu ga, Nani ka? 254"},
        {'href': r'http://raisingthedead.ninja/2016/02/21/kumo-desu-ga-nani-ka-255/',
         'title': "Kumo desu ga, Nani ka? 255"},
        {'href': r'http://raisingthedead.ninja/2016/02/22/kumo-desu-ga-nani-ka-256/',
         'title': "Kumo desu ga, Nani ka? 256"},
        {'href': r'http://raisingthedead.ninja/2016/02/23/kumo-desu-ga-nani-ka-blood-27/',
         'title': "Kumo desu ga, Nani ka? Blood 27"},
        {'href': r'http://raisingthedead.ninja/2016/02/24/kumo-desu-ga-nani-ka-oni-11/',
         'title': "Kumo desu ga, Nani ka? Oni 11"},
        {'href': r'http://raisingthedead.ninja/2016/02/25/kumo-desu-ga-nani-ka-blood-28/',
         'title': "Kumo desu ga, Nani ka? Blood 28"},
        {'href': r'http://raisingthedead.ninja/2016/02/26/kumo-desu-ga-nani-ka-oni-12/',
         'title': "Kumo desu ga, Nani ka? Oni 12"},
        {'href': r'http://raisingthedead.ninja/2016/02/27/kumo-desu-ga-nani-ka-blood-29/',
         'title': "Kumo desu ga, Nani ka? Blood 29"},
        {'href': r'http://raisingthedead.ninja/2016/02/28/kumo-desu-ga-nani-ka-oni-13/',
         'title': "Kumo desu ga, Nani ka? Oni 13"},
        {'href': r'http://raisingthedead.ninja/2016/02/29/kumo-desu-ga-nani-ka-blood-30/',
         'title': "Kumo desu ga, Nani ka? Blood 30"},
        {'href': r'http://raisingthedead.ninja/2016/03/04/kumo-desu-ga-nani-ka-257/',
         'title': "Kumo desu ga, Nani ka? 257"},
        {'href': r'http://raisingthedead.ninja/2016/03/05/kumo-desu-ga-nani-ka-the-popes-deliberations/',
         'title': "Kumo Desu ga, Nani ka? The Pope’s Deliberations"},
        {'href': r'http://raisingthedead.ninja/2016/03/06/kumo-desu-ga-nani-ka-the-popes-torment/',
         'title': "Kumo Desu ga, Nani ka? The Pope’s Torment"},
        {'href': r'http://raisingthedead.ninja/2016/03/07/kumo-desu-ga-nani-ka-258/',
         'title': "Kumo desu ga, Nani ka? 258"},
        {'href': r'http://raisingthedead.ninja/2016/03/09/kumo-desu-ga-nani-ka-259/',
         'title': "Kumo desu ga, Nani ka? 259"},
        {'href': r'http://raisingthedead.ninja/2016/03/11/kumo-desu-ga-nani-ka-oni-14/',
         'title': "Kumo desu ga, Nani ka? Oni 14"},
        {'href': r'http://raisingthedead.ninja/2016/03/14/kumo-desu-ga-nani-ka-blood-31/',
         'title': "Kumo desu ga, Nani ka? Blood 31"},
        {'href': r'http://raisingthedead.ninja/2016/03/16/kumo-desu-ga-nani-ka-260/',
         'title': "Kumo desu ga, Nani ka? 260"},
        {'href': r'http://raisingthedead.ninja/2016/06/17/the-return-of-the-spider/',
         'title': "The Return of the Spider"},
        {'href': r'http://raisingthedead.ninja/2016/06/17/kumo-desu-ga-nani-ka-oni-15/',
         'title': "Kumo desu ga, Nani ka? Oni 15"},
        {'href': r'http://raisingthedead.ninja/2016/06/18/kumo-desu-ga-nani-ka-blood-32/',
         'title': "Kumo desu ga, Nani ka? Blood 32"},
        {'href': r'http://raisingthedead.ninja/2016/06/19/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a0/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ①"},
        {'href': r'http://raisingthedead.ninja/2016/06/19/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a1/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ②"},
        {'href': r'http://raisingthedead.ninja/2016/06/20/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a2/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ③"},
        {'href': r'http://raisingthedead.ninja/2016/06/20/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a3/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ④"},
        {'href': r'http://raisingthedead.ninja/2016/06/21/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a4/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑤"},
        {'href': r'http://raisingthedead.ninja/2016/06/22/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a5/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑥"},
        {'href': r'http://raisingthedead.ninja/2016/06/23/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a6/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑦"},
        {'href': r'http://raisingthedead.ninja/2016/06/24/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a7/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑧"},
        {'href': r'http://raisingthedead.ninja/2016/07/01/kumo-desu-ga-nani-ka-informal-conference-%e2%91%a8/',
         'title': "Kumo desu ga, Nani ka? Informal Conference ⑨"},
        {'href': r'http://raisingthedead.ninja/2016/07/02/kumo-desu-ga-nani-ka-informal-conference-hidden/',
         'title': "Kumo desu ga, Nani ka? Informal Conference &#8211; hidden"},
        {'href': r'http://raisingthedead.ninja/2016/07/02/kumo-desu-ga-nani-ka-oni-16/',
         'title': "Kumo desu ga, Nani ka? Oni 16"},
        {'href': r'http://raisingthedead.ninja/2016/07/03/kumo-desu-ga-nani-ka-blood-33/',
         'title': "Kumo desu ga, Nani ka? Blood 33"},
        {'href': r'http://raisingthedead.ninja/2016/07/07/kumo-desu-ga-nani-ka-oni-17/',
         'title': "Kumo desu ga, Nani ka? Oni 17"},
        {'href': r'http://raisingthedead.ninja/2016/07/10/kumo-desu-ga-nani-ka-261/',
         'title': "Kumo desu ga, Nani ka? 261"},
        {'href': r'http://raisingthedead.ninja/2016/07/16/kumo-desu-ga-nani-ka-262/',
         'title': "Kumo desu ga, Nani ka? 262"},
        {'href': r'http://raisingthedead.ninja/2016/07/24/kumo-desu-ga-nani-ka-263/',
         'title': "Kumo desu ga, Nani ka? 263"},
        {'href': r'http://raisingthedead.ninja/2016/07/31/kumo-desu-ga-nani-ka-264/',
         'title': "Kumo desu ga, Nani ka? 264"},
        {'href': r'http://raisingthedead.ninja/2016/08/16/kumo-desu-ga-nani-ka-265/',
         'title': "Kumo desu ga, Nani ka? 265"},
        {
            'href': r'http://raisingthedead.ninja/2016/08/23/kumo-desu-ga-nani-ka-the-second-informal-conference-%e2%91%a0/',
            'title': "Kumo desu ga, Nani ka? The Second Informal Conference ①"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/07/kumo-desu-ga-nani-ka-the-second-informal-conference-%e2%91%a1/',
            'title': "Kumo desu ga, Nani ka? The Second Informal Conference ②"},
        {'href': r'http://raisingthedead.ninja/2016/09/10/kumo-desu-ga-nani-ka-the-demon-king-and-the-pope/',
         'title': "Kumo desu ga, Nani ka? The Demon King and the Pope"},
        {'href': r'http://raisingthedead.ninja/2016/09/11/kumo-desu-ga-nani-ka-the-oni-and-the-ninja/',
         'title': "Kumo desu ga, Nani ka? The Oni and the Ninja"},
        {'href': r'http://raisingthedead.ninja/2016/09/11/kumo-desu-ga-nani-ka-the-vampire-the-oni-and-the-ninja/',
         'title': "Kumo desu ga, Nani ka? The Vampire, the Oni and the Ninja"},
        {'href': r'http://raisingthedead.ninja/2016/09/11/kumo-desu-ga-nani-ka-266/',
         'title': "Kumo desu ga, Nani ka? 266"},
        {'href': r'http://raisingthedead.ninja/2016/09/16/kumo-desu-ga-nani-ka-267/',
         'title': "Kumo desu ga, Nani ka? 267"},
        {'href': r'http://raisingthedead.ninja/2016/09/17/kumo-desu-ga-nani-ka-268/',
         'title': "Kumo desu ga, Nani ka? 268"},
        {'href': r'http://raisingthedead.ninja/2016/09/18/kumo-desu-ga-nani-ka-269/',
         'title': "Kumo desu ga, Nani ka? 269"},
        {'href': r'http://raisingthedead.ninja/2016/09/19/kumo-desu-ga-nani-ka-270/',
         'title': "Kumo desu ga, Nani ka? 270"},
        {'href': r'http://raisingthedead.ninja/2016/09/19/kumo-desu-ga-nani-ka-271/',
         'title': "Kumo desu ga, Nani ka? 271"},
        {'href': r'http://raisingthedead.ninja/2016/09/20/kumo-desu-ga-nani-ka-272/',
         'title': "Kumo desu ga, Nani ka? 272"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/21/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-tagawa-kunihiko/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War &#8211; The situation of Tagawa Kunihiko"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/22/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-kushitani-asaka-and-orel/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Kushitani Asaka and Aurel"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/23/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-merazofis/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Merazofis"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/24/kumo-desu-ga-nani-ka-before-the-human-demon-great-war-the-situation-of-ronant/',
            'title': "Kumo desu ga, Nani ka? Before The Human-Demon Great War &#8211; The situation of Ronant"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/25/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-wrath/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War &#8211; The situation of Wrath"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/26/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-sophia/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Sophia"},
        {
            'href': r'http://raisingthedead.ninja/2016/09/27/kumo-desu-ga-nani-ka-the-human-demon-great-war-the-situation-of-blow/',
            'title': "Kumo desu ga, Nani ka? The Human-Demon Great War – The situation of Blow"},
        {'href': r'http://raisingthedead.ninja/2016/09/28/kumo-desu-ga-nani-ka-273/',
         'title': "Kumo desu ga, Nani ka? 273"},
        {'href': r'http://raisingthedead.ninja/2016/09/29/kumo-desu-ga-nani-ka-274/',
         'title': "Kumo desu ga, Nani ka? 274"},
        {'href': r'http://raisingthedead.ninja/2016/09/30/kumo-desu-ga-nani-ka-275/',
         'title': "Kumo desu ga, Nani ka? 275"},
        {'href': r'http://raisingthedead.ninja/2016/10/05/kumo-desu-ga-nani-ka-276/',
         'title': "Kumo desu ga, Nani ka? 276"},
        {'href': r'http://raisingthedead.ninja/2016/10/06/kumo-desu-ga-nani-ka-277/',
         'title': "Kumo desu ga, Nani ka? 277"},
        {'href': r'http://raisingthedead.ninja/2016/10/08/kumo-desu-ga-nani-ka-278/',
         'title': "Kumo desu ga, Nani ka? 278"},
        {'href': r'http://raisingthedead.ninja/2016/10/09/kumo-desu-ga-nani-ka-279/',
         'title': "Kumo desu ga, Nani ka? 279"},
        {'href': r'http://raisingthedead.ninja/2016/10/10/kumo-desu-ga-nani-ka-280/',
         'title': "Kumo desu ga, Nani ka? 280"},
        {'href': r'http://raisingthedead.ninja/2016/10/14/kumo-desu-ga-nani-ka-the-elf-leaders-miscalculation/',
         'title': "Kumo desu ga, Nani ka? The Elf Leader’s Miscalculation"},
        {'href': r'http://raisingthedead.ninja/2016/10/16/kumo-desu-ga-nani-ka-blood-34/',
         'title': "Kumo desu ga, Nani ka? Blood 34"},
        {'href': r'http://raisingthedead.ninja/2016/10/18/kumo-desu-ga-nani-ka-oni-18/',
         'title': "Kumo desu ga, Nani ka? Oni 18"},
        {'href': r'http://raisingthedead.ninja/2016/10/23/kumo-desu-ga-nani-ka-281/',
         'title': "Kumo desu ga, Nani ka? 281"},
        {'href': r'http://raisingthedead.ninja/2016/10/24/kumo-desu-ga-nani-ka-282/',
         'title': "Kumo desu ga, Nani ka? 282"},
        {'href': r'http://raisingthedead.ninja/2016/10/25/kumo-desu-ga-nani-ka-a-flat-chest-is-a-status-symbol/',
         'title': "Kumo desu ga, Nani ka? A flat chest is a status symbol!"},
        {'href': r'http://raisingthedead.ninja/2016/10/28/kumo-desu-ga-nani-ka-283/',
         'title': "Kumo desu ga, Nani ka? 283"},
        {
            'href': r'http://raisingthedead.ninja/2016/10/30/kumo-desu-ga-nani-ka-the-third-informal-conference-%e2%91%a0/',
            'title': "Kumo desu ga, Nani ka? The Third Informal Conference ①"},
        {
            'href': r'http://raisingthedead.ninja/2016/11/01/kumo-desu-ga-nani-ka-the-third-informal-conference-%e2%91%a1/',
            'title': "Kumo desu ga, Nani ka? The Third Informal Conference ②"},
        {'href': r'http://raisingthedead.ninja/2016/11/01/kumo-desu-ga-nani-ka-ss-halloween/',
         'title': "Kumo desu ga, Nani ka? SS &#8211; Halloween"},
        {'href': r'http://raisingthedead.ninja/2016/11/03/kumo-desu-ga-nani-ka-angry-oni/',
         'title': "Kumo desu ga, Nani ka? Angry Oni"},
        {'href': r'http://raisingthedead.ninja/2016/11/06/kumo-desu-ga-nani-ka-insane-oni/',
         'title': "Kumo desu ga, Nani ka? Insane Oni"},
        {'href': r'http://raisingthedead.ninja/2016/11/07/kumo-desu-ga-nani-ka-tipsy/',
         'title': "Kumo desu ga, Nani ka? Tipsy"},
        {'href': r'http://raisingthedead.ninja/2016/11/12/kumo-desu-ga-nani-ka-blood-35/',
         'title': "Kumo desu ga, Nani ka? Blood 35"},
        {'href': r'http://raisingthedead.ninja/2016/11/14/kumo-desu-ga-nani-ka-oni-19/',
         'title': "Kumo desu ga, Nani ka? Oni 19"},
        {'href': r'http://raisingthedead.ninja/2016/11/15/kumo-desu-ga-nani-ka-284/',
         'title': "Kumo desu ga, Nani ka? 284"},
        {'href': r'http://raisingthedead.ninja/2016/12/13/kumo-desu-ga-nani-ka-ss-autumn-leaf-viewing/',
         'title': "Kumo desu ga, Nani ka? SS Autumn-leaf Viewing"},
        {'href': r'http://raisingthedead.ninja/2016/12/22/kumo-desu-ga-nani-ka-timeline/',
         'title': "Kumo desu ga, Nani ka? Timeline"},
        {'href': r'http://raisingthedead.ninja/2016/12/30/kumo-desu-ga-nani-ka-285/',
         'title': "Kumo desu ga, Nani ka? 285"},
        {'href': r'http://raisingthedead.ninja/2017/01/01/kumo-desu-ga-nani-ka-286/',
         'title': "Kumo desu ga, Nani ka? 286"},
        {'href': r'http://raisingthedead.ninja/2017/01/02/kumo-desu-ga-nani-ka-ss-new-years-eve-soba/',
         'title': "Kumo desu ga, Nani ka? SS &#8211; New Year&#8217;s Eve Soba"},
        {'href': r'http://raisingthedead.ninja/2017/01/13/kumo-desu-ga-nani-ka-287/',
         'title': "Kumo desu ga, Nani ka? 287"},
        {'href': r'http://raisingthedead.ninja/2017/01/15/kumo-desu-ga-nani-ka-288/',
         'title': "Kumo desu ga, Nani ka? 288"},
        {'href': r'http://raisingthedead.ninja/2017/02/19/kumo-desu-ga-nani-ka-ss-valentine/',
         'title': "Kumo desu ga, Nani ka? SS – Valentine"},
        {'href': r'http://raisingthedead.ninja/2017/02/20/kumo-desu-ga-nani-ka-289/',
         'title': "Kumo desu ga, Nani ka? 289"},
        {'href': r'http://raisingthedead.ninja/2017/02/21/kumo-desu-ga-nani-ka-290/',
         'title': "Kumo desu ga, Nani ka? 290"},
        {'href': r'http://raisingthedead.ninja/2017/02/22/kumo-desu-ga-nani-ka-291/',
         'title': "Kumo desu ga, Nani ka? 291 – Elf Village Battle ①"},
        {'href': r'http://raisingthedead.ninja/2017/02/22/kumo-desu-ga-nani-ka-292/',
         'title': "Kumo desu ga, Nani ka? 292 &#8211; Elf Village Battle ②"},
        {'href': r'http://raisingthedead.ninja/2017/02/24/kumo-desu-ga-nani-ka-293/',
         'title': "Kumo desu ga, Nani ka? 293 &#8211; Elf Village Battle ③"},
        {'href': r'http://raisingthedead.ninja/2017/02/26/kumo-desu-ga-nani-ka-294/',
         'title': "Kumo desu ga, Nani ka? 294 &#8211; Elf Village Battle ④"},
        {'href': r'http://raisingthedead.ninja/2017/02/27/kumo-desu-ga-nani-ka-295/',
         'title': "Kumo desu ga, Nani ka? 295 &#8211; Elf Village Battle ⑤"},
        {'href': r'http://raisingthedead.ninja/2017/02/27/elf-village-battle-%e2%91%a5/',
         'title': "Kumo desu ga, Nani ka? Elf Village Battle ⑥"},
        {'href': r'http://raisingthedead.ninja/2017/03/03/kumo-desu-ga-nani-ka-elf-village-battle-%e2%91%a6/',
         'title': "Kumo desu ga, Nani ka? Elf Village Battle ⑦"},
        {'href': r'http://raisingthedead.ninja/2017/03/08/kumo-desu-ga-nani-ka-296/',
         'title': "Kumo desu ga, Nani ka? 296 &#8211; Elf Village Battle ⑧"},
        {'href': r'http://raisingthedead.ninja/2017/03/09/kumo-desu-ga-nani-ka-297/',
         'title': "Kumo desu ga, Nani ka? 297 &#8211; Elf Village Battle ⑨"},
        {'href': r'http://raisingthedead.ninja/2017/03/10/kumo-desu-ga-nani-ka-298/',
         'title': "Kumo desu ga, Nani ka? 298 &#8211; Elf Village Battle ⑩"},
        {'href': r'http://raisingthedead.ninja/2017/03/12/kumo-desu-ga-nani-ka-299/',
         'title': "Kumo desu ga, Nani ka? 299 &#8211; Elf Village Battle ⑪"},
        {'href': r'http://raisingthedead.ninja/2017/03/13/kumo-desu-ga-nani-ka-300/',
         'title': "Kumo desu ga, Nani ka? 300"},
        {'href': r'http://raisingthedead.ninja/2017/03/18/kumo-desu-ga-nani-ka-the-dreaming-boy/',
         'title': "Kumo desu ga, Nani ka? The dreaming boy"},
        {'href': r'http://raisingthedead.ninja/2017/03/19/kumo-desu-ga-nani-ka-past-arc-%e2%91%a0/',
         'title': "Kumo desu ga, Nani ka? Past Arc ①"},
        {'href': r'http://raisingthedead.ninja/2017/05/19/kumo-desu-ga-nani-ka-past-arc-%e2%91%a1/',
         'title': "Kumo desu ga, Nani ka? Past Arc ②"},
        {'href': r'http://raisingthedead.ninja/2017/05/20/kumo-desu-ga-nani-ka-past-arc-%e2%91%a2/',
         'title': "Kumo desu ga, Nani ka? Past Arc ③"},
        {'href': r'http://raisingthedead.ninja/2017/05/21/kumo-desu-ga-nani-ka-past-arc-%e2%91%a3/',
         'title': "Kumo desu ga, Nani ka? Past Arc ④"},
        {'href': r'http://raisingthedead.ninja/2017/05/21/oshiete-d-sensei-lesson-2/',
         'title': "Oshiete D-sensei! Lesson 2"},
        {'href': r'http://raisingthedead.ninja/2017/05/22/kumo-desu-ga-nani-ka-past-arc-%e2%91%a4/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑤"},
        {'href': r'http://raisingthedead.ninja/2017/05/22/kumo-desu-ga-nani-ka-past-arc6/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑥"},
        {'href': r'http://raisingthedead.ninja/2017/05/24/kumo-desu-ga-nani-ka-past-arc-%e2%91%a6/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑦"},
        {'href': r'http://raisingthedead.ninja/2017/05/25/kumo-desu-ga-nani-ka-past-arc-%e2%91%a7/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑧"},
        {'href': r'http://raisingthedead.ninja/2017/05/27/kumo-desu-ga-nani-ka-past-arc-%e2%91%a8/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑨"},
        {'href': r'http://raisingthedead.ninja/2017/06/03/kumo-desu-ga-nani-ka-past-arc-%e2%91%a9/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑩"},
        {'href': r'http://raisingthedead.ninja/2017/06/14/kumo-desu-ga-nani-ka-past-arc-%e2%91%aa/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑪"},
        {'href': r'http://raisingthedead.ninja/2017/06/24/kumo-desu-ga-nani-ka-past-arc-%e2%91%ab/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑫"},
        {'href': r'http://raisingthedead.ninja/2017/08/09/kumo-desu-ga-nani-ka-past-arc-%e2%91%ac/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑬"},
        {'href': r'http://raisingthedead.ninja/2017/08/13/kumo-desu-ga-nani-ka-past-arc-%e2%91%ad/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑭"},
        {'href': r'http://raisingthedead.ninja/2017/08/14/kumo-desu-ga-nani-ka-past-arc-%e2%91%ae/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑮"},
        {'href': r'http://raisingthedead.ninja/2017/08/22/kumo-desu-ga-nani-ka-past-arc-%e2%91%af/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑯"},
        {'href': r'http://raisingthedead.ninja/2017/08/23/kumo-desu-ga-nani-ka-past-arc-%e2%91%b0/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑰"},
        {'href': r'http://raisingthedead.ninja/2017/08/27/kumo-desu-ga-nani-ka-past-arc-%e2%91%b1/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑱"},
        {'href': r'http://raisingthedead.ninja/2017/08/30/kumo-desu-ga-nani-ka-past-arc-%e2%91%b2/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑲"},
        {'href': r'http://raisingthedead.ninja/2017/09/01/kumo-desu-ga-nani-ka-past-arc-%e2%91%b3/',
         'title': "Kumo desu ga, Nani ka? Past Arc ⑳"},
        {'href': r'http://raisingthedead.ninja/2017/09/03/kumo-desu-ga-nani-ka-past-arc-%e3%89%91/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉑"},
        {'href': r'http://raisingthedead.ninja/2017/09/04/kumo-desu-ga-nani-ka-past-arc-%e3%89%92/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉒"},
        {'href': r'http://raisingthedead.ninja/2017/09/04/kumo-desu-ga-nani-ka-past-arc-%e3%89%93/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉓"},
        {'href': r'http://raisingthedead.ninja/2017/09/06/kumo-desu-ga-nani-ka-past-arc-%e3%89%94/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉔"},
        {'href': r'http://raisingthedead.ninja/2017/09/07/kumo-desu-ga-nani-ka-past-arc-%e3%89%95/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉕"},
        {'href': r'http://raisingthedead.ninja/2017/09/09/kumo-desu-ga-nani-ka-past-arc-%e3%89%96/',
         'title': "Kumo desu ga, Nani ka? Past Arc ㉖"},
        {'href': r'http://raisingthedead.ninja/2017/09/11/kumo-desu-ga-nani-ka-past-reflections-ariel/',
         'title': "Kumo desu ga, Nani ka? Past Reflections: Ariel"},
        {'href': r'http://raisingthedead.ninja/2017/09/12/kumo-desu-ga-nani-ka-past-reflections-gyurie/',
         'title': "Kumo desu ga, Nani ka? Past Reflections: Gyurie"},
        {'href': r'http://raisingthedead.ninja/2017/09/18/kumo-desu-ga-nani-ka-character-introduction-2/',
         'title': "Kumo desu ga, Nani ka? Character Introduction 2"},
        {'href': r'http://raisingthedead.ninja/2017/09/18/kumo-desu-ga-nani-ka-oshiete-d-sensei-lesson-3/',
         'title': "Kumo desu ga, Nani ka? Oshiete D-sensei! Lesson 3"},
        {'href': r'http://raisingthedead.ninja/2017/09/19/kumo-desu-ga-nani-ka-301/',
         'title': "Kumo desu ga, Nani ka? 301"},
        {'href': r'http://raisingthedead.ninja/2017/09/19/kumo-desu-ga-nani-ka-302/',
         'title': "Kumo desu ga, Nani ka? 302"},
        {'href': r'http://raisingthedead.ninja/2017/09/19/kumo-desu-ga-nani-ka-303/',
         'title': "Kumo desu ga, Nani ka? 303"},
        {'href': r'http://raisingthedead.ninja/2017/09/20/kumo-desu-ga-nani-ka-304/',
         'title': "Kumo desu ga, Nani ka? 304"},
        {'href': r'http://raisingthedead.ninja/2017/09/21/kumo-desu-ga-nani-ka-305/',
         'title': "Kumo desu ga, Nani ka? 305"},
        {'href': r'http://raisingthedead.ninja/2017/09/22/kumo-desu-ga-nani-ka-s30/',
         'title': "Kumo desu ga, Nani ka? S30"},
        {'href': r'http://raisingthedead.ninja/2017/09/23/kumo-desu-ga-nani-ka-306/',
         'title': "Kumo desu ga, Nani ka? 306"},
        {'href': r'http://raisingthedead.ninja/2017/09/24/kumo-desu-ga-nani-ka-307/',
         'title': "Kumo desu ga, Nani ka? 307"},
        {'href': r'http://raisingthedead.ninja/2017/09/28/kumo-desu-ga-nani-ka-308/',
         'title': "Kumo desu ga, Nani ka? 308"},
        {'href': r'http://raisingthedead.ninja/2017/09/30/kumo-desu-ga-nani-ka-309/',
         'title': "Kumo desu ga, Nani ka? 309"},
        {'href': r'http://raisingthedead.ninja/2017/10/04/kumo-desu-ga-nani-ka-310/',
         'title': "Kumo desu ga, Nani ka? 310"},
        {'href': r'http://raisingthedead.ninja/2017/10/15/kumo-desu-ga-nani-ka-s31/',
         'title': "Kumo desu ga, Nani ka? S31"},
        {'href': r'http://raisingthedead.ninja/2017/12/18/kumo-desu-ga-nani-ka-311/',
         'title': "Kumo desu ga, Nani ka? 311"},
        {'href': r'http://raisingthedead.ninja/2017/12/18/kumo-desu-ga-nani-ka-312/',
         'title': "Kumo desu ga, Nani ka? 312"},
        {'href': r'http://raisingthedead.ninja/2017/12/18/kumo-desu-ga-nani-ka-313/',
         'title': "Kumo desu ga, Nani ka? 313"},
        {'href': r'http://raisingthedead.ninja/2018/01/15/kumo-desu-ga-nani-ka-314/',
         'title': "Kumo desu ga, Nani ka? 314"},
        {'href': r'http://raisingthedead.ninja/2018/01/16/kumo-desu-ga-nani-ka-315/',
         'title': "Kumo desu ga, Nani ka? 315"},
        {'href': r'http://raisingthedead.ninja/2018/02/04/kumo-desu-ga-nani-ka-s32/',
         'title': "Kumo desu ga, Nani ka? S32"},
        {'href': r'http://raisingthedead.ninja/2018/02/04/kumo-desu-ga-nani-ka-oshiete-d-sensei-lesson-4/',
         'title': "Kumo desu ga, Nani ka? Oshiete D-sensei! Lesson 4"},
        {'href': r'http://raisingthedead.ninja/2018/02/05/kumo-desu-ga-nani-ka-316/',
         'title': "Kumo desu ga, Nani ka? 316"}
    ]
    out = r'Out\RAD'
    out_htmls = []
    out_titles = []
    for i in range(0,len(files)-1):
        base_name = os.path.split(os.path.split(files[i]['href'])[0])[1]
        curr_html = os.path.join(out,str(i)+"_"+base_name+".html")
        out_html = os.path.join(out,str(i)+"_"+base_name+"_out.html")
        print("Page "+str(i))
        out_htmls.append(out_html)
        out_titles.append(files[i]['title'])
        if os.path.exists(curr_html):
            with open(curr_html,'rb') as f:
                txt = f.read().decode("utf-8")
        else:
            txt = downloadFile(files[i]['href'])
        soup = BeautifulSoup(txt, 'html.parser')
        body=soup.find_all('div',class_='entry-content')
        ps = body[0].find_all('p')
        with open(out_html,'wb') as f:
            for p in ps:
                if(p.find_all('div',class_="saboxplugin-wrap")):
                    continue
                if(p.find_all('iframe')):
                    continue
                f.write(str(p).encode("utf-8")+b'\n')
    book = epub.EpubBook()

    # set metadata
    book.set_identifier('id121234')
    book.set_title('Kumo Desu Ga? Nani ka? (Chap 213-315)')
    book.set_language('en')
    book.set_cover("image.jpg", open(r'bookcover\kumorad.jpg', 'rb').read())
    book.add_author('Baba Okina')

    spine = ['nav']
    toc = []
    for i in range(0,len(out_htmls)-1):
        base_name = os.path.splitext(os.path.basename(out_htmls[i]))[0].replace("%","_")
        # create chapter
        c1 = epub.EpubHtml(title=out_titles[i], file_name=base_name+".xhtml")
        with open(out_htmls[i],'rb') as f:
            c1.content=f.read()
        spine.append(c1)
        toc.append(c1)
        # add chapter
        book.add_item(c1)

    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = spine
    book.toc = (toc)
    # write to the file
    epub.write_epub(os.path.join(out,"Kumo_RAD.epub"), book, {})

def start_book(series):
    book = epub.EpubBook()
    book.set_identifier('id1234534' + str(series))
    book.set_title('蜘蛛ですが、なにか？ ' + str(series))
    book.set_language('jp')
    img = Image.open(r'bookcover\kumorad.jpg')
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), str(series), (255, 255, 255), font=ImageFont.truetype("arial.ttf", 200))
    img_file = BytesIO()
    img.save(img_file, 'jpeg')
    book.set_cover("image.jpg", img_file.getvalue())
    book.add_author('馬場翁')
    return book

def end_book(book,series, spine, toc, outdir):
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = spine
    book.toc = (toc)
    epub.write_epub(os.path.join(outdir, "Kumo_Desuka_%s.epub" % str(series)), book, {})

def original():
    base_url = r'http://ncode.syosetu.com/'
    ind = 'n7975cr'
    outdir = 'Out\Original'
    def get_chaps():
        ind_html = BeautifulSoup(downloadFile(base_url+"/"+ind),'html.parser')
        toc_body = ind_html.find_all("div",class_="index_box")[0]
        chaps_tags = toc_body.find_all("a")
        chaps = []
        for c in chaps_tags:
            chaps.append({'href':c['href'],'title':c.get_text()})
        return chaps
    chaps = get_chaps()
    out_htmls = []
    out_titles = []

    series = 1
    book = start_book(series)
    spine = ['nav']
    toc = []
    cnt = 0
    for c in chaps:
        if (cnt % 100)==99:
            end_book(book,series, spine,toc,outdir)
            series+=1
            book = start_book(series)
            spine = ['nav']
            toc = []
            cnt = 0
        print("Chapter "+c['title']+" "+c['href'])
        base_name = c['href'].split("/")[-2]
        curr_html = os.path.join(outdir,base_name+".html")
        out_htmls.append(curr_html)
        out_titles.append(c['title'])
        if os.path.exists(curr_html):
            with open(curr_html,'rb') as f:
                txt = f.read().decode("utf-8")
        else:
            txt = downloadFile(base_url+c['href'])
            with open(curr_html, 'wb') as f:
                f.write(txt.encode("utf-8"))
        c_tags = BeautifulSoup(txt,'html.parser')
        body = c_tags.find(id="novel_honbun")
        echap = epub.EpubHtml(title=c['title'],file_name=base_name+".xhtml")
        echap.content = "<strong>%s</strong>\n" % c['title']+body.decode_contents()
        spine.append(echap)
        toc.append(echap)
        book.add_item(echap)
        cnt+=1
    end_book(book,series, spine,toc,outdir)

#tubosquid()
#raisedead()
original()