name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build -- --env=version=1.3.${{ github.run_number }}
      - name: Zip chrome
        run: zip -qq -r chrome.zip *
        working-directory: dist/chrome_prod
      - run: npm run build_ff -- --env=version=1.3.${{ github.run_number }}
      - name: Zip firefox
        run: zip -qq -r firefox.zip *
        working-directory: dist/firefox_prod
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/chrome_prod/chrome.zip
            dist/firefox_pod/firefox.zip
