name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build -- --env=version=1.3.${{ github.run_number }}
      - run: npm run build_ff -- --env=version=1.3.${{ github.run_number }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-chrome
          path: |
            dist/chrome_prod
            dist/firefox_prod
